### ISSUE TITLE
HLS Direct streaming mode doesn't support playing songs

### ISSUE THREAD

**Issue by jquerijero** [ErsatzTV/ErsatzTV#1001]
I'm just wondering if I need to set the Streaming Mode to something specific for songs (MP3), or if Kodi itself is not able to play the media file.

**Comment by jasongdove** [comment]
It looks like `HLS Direct` streaming mode doesn't properly handle songs. I'll work on fixing that, but for now you will probably want to use `HLS Segmenter`.

**Comment by second2falcon** [comment]
> It looks like `HLS Direct` streaming mode doesn't properly handle songs. I'll work on fixing that, but for now you will probably want to use `HLS Segmenter`.

Just found this issue as I switched from dizqueTV to ErsatzTV and this indeed did the trick. For some reason the stream on Plex still stutters at times, but works flawlessly on VLC directly (probably the CPU sweating as both Plex and ErsatzTV are in kubernetes containers on my TrueNAS server).
