### ISSUE TITLE
[Feature request] ability to schedule things in the scheduler.

### ISSUE THREAD

**Issue by kbhors** [ErsatzTV/ErsatzTV#1013]
The schedule doesn't have anywhere to enter a start time.

I think it would be good if it did. For example, If I want to broadcast an episode of Plastic Surgery Disasters at 2PM, I should be able to click on it in the schedule, type "14:00", and then the program would know to play it then.

**Comment by mattroark** [comment]
Based on my experience (and supporting documentation - at least for the current release), this may be accomplished via specifying the Start Type as `Fixed`, and then setting the `Start Time`.

https://ersatztv.org/user-guide/create-channels/#start-type

> Items with a Dynamic start type will start immediately after the preceding schedule item, while a Fixed start type requires a start time.
