### ISSUE TITLE
All seasons get indexed as s00 (Specials)

### ISSUE THREAD

**Issue by krutburken** [ErsatzTV/ErsatzTV#1103]
Kind of an odd issue. Been trying ersatztv again to check on the progress on the project, and noticed that all seasons in shows are named "Specials". The shows are synced from Jellyfin (10.8.8) and are properly named there. When looking closer, they all seem to get indexed as s00 which I guess is the root cause. No errors in logs when syncing the shows. 

Some examples:
![Screenshot 2023-01-08 at 20 20 24](https://user-images.githubusercontent.com/13684929/211215044-12329db6-29cb-4cea-bce8-f018cceef723.png)
![Screenshot 2023-01-08 at 20 35 40](https://user-images.githubusercontent.com/13684929/211215326-732bb418-8aff-4f3d-a814-2bfa5c74aa33.png)
![Screenshot 2023-01-08 at 20 24 20](https://user-images.githubusercontent.com/13684929/211215049-49ae77ef-ff6c-42b0-8111-af7e363988c4.png)

app version is: 0.7.2-ba676ef9-docker-nvidia

**Comment by jasongdove** [comment]
Season number is returned as `IndexNumber` from the Jellyfin Items API

https://github.com/jasongdove/ErsatzTV/blob/9479806cb06c839b17f5063cbbcaa62dac033c2a/ErsatzTV.Infrastructure/Jellyfin/JellyfinApiClient.cs#L669-L672

Searching for an open Jellyfin issue about season numbers, I see that you previously reported season numbers missing within Jellyfin here https://github.com/jellyfin/jellyfin/issues/4948

This might be related. Will give it some more thought.

**Comment by krutburken** [comment]
Oh, I've completely forgot about that issue, though from what I remember it was due to the tvdb plugin (it started working normally again when jellyfin stable was released). I did try ErsatzTV on this same server maybe 6 months ago, and this issue was not present

**Comment by krutburken** [comment]
Just a quick update. I tried this again with the latest nvidia-develop on a fresh ersatztv install, and the issue is still there.

**Comment by jasongdove** [comment]
It would help if you're able to hop in our discord and send me a dm, I think we'll need to dive into the Jellyfin API to see why your server is giving that result.

**Comment by mxerist** [comment]
Hi, sorry for the extremely slow reply (haven't used ersatztv in a while). Tried again with the latest docker-nvidia, and this is still a thing. I don't use Discord unfortunately, but I can supply the necessary info here if that works. 

Could you tell me how the season index in ersatztv is decided so I can maybe have a look at the metadata in jellyfin? Some shows are fine, but most are listed as s00. Should be pretty easy to compare the two if I know what to look for.

**Comment by krutburken** [comment]
Hi, sorry for the extremely slow reply (haven't used ersatztv in a while). Tried again with the latest docker-nvidia, and this is still a thing. I don't use Discord unfortunately, but I can supply the necessary info here if that works.

Could you tell me how the season index in ersatztv is decided so I can maybe have a look at the metadata in jellyfin? Some shows are fine, but most are listed as s00. Should be pretty easy to compare the two if I know what to look for.

**Comment by krutburken** [comment]
After some investigation it seems my seasons IndexNumber in the db was mostly set to NULL. I updated them and ersatztv is now picking up the correct season numbers. For reference if someone else hits the same issue:

```
update TypedBaseItems
set IndexNumber=1
where type="MediaBrowser.Controller.Entities.TV.Season" and (CleanName="s01" or CleanName="season 1") and IndexNumber is NULL
```
