### ISSUE TITLE
Error run on MacOS Big Sur

### ISSUE THREAD

**Issue by berny6969** [ErsatzTV/ErsatzTV#1131]
hi when run dmg x64 on macmini big sur get message "You are not authorized to open the “ErsatzTV” application. Contact the administrator for assistance."

tested dmg from 0.4.5 to last release, cannot work too launch with sudo 

how to use this app?

always download x64 release ErsatzTV-v0.7.2-beta-osx-x64

thanks

**Comment by scoobshub** [comment]
I run this in terminal to get it to work:
`codesign --force --deep --sign - /Applications/ErsatzTV.app`

**Comment by jasongdove** [comment]
Looks like github recently changed their builds to run on macos-12 instead of macos-11. I'll specifically use macos-11 and see if that gets things working again. https://github.com/jasongdove/ErsatzTV/pull/1132

**Comment by jasongdove** [comment]
FWIW the MacOS artifacts have been properly signed and notarized for a long time. See https://github.com/jasongdove/ErsatzTV/blob/main/scripts/macOS/sign.sh

It seems like sometimes signing on a newer version of MacOS will create signatures that aren't seen as valid on older versions. Will see once the develop build completes.

**Comment by jasongdove** [comment]
Please test with the latest develop release https://github.com/jasongdove/ErsatzTV/releases/tag/develop

**Comment by berny6969** [comment]
> Please test with the latest develop release https://github.com/jasongdove/ErsatzTV/releases/tag/develop

Same error with developer release

Only launch with codesign command on this issue

**Comment by jasongdove** [comment]
Thanks. I'll try to get a local Big Sur installation where I can test.
