### ISSUE TITLE
Support for loading embedded subtitles in HLS Direct streaming mode

### ISSUE THREAD

**Issue by garygan89** [ErsatzTV/ErsatzTV#1138]
Long time user here since 0.6.x! Just wondering if it is possible to load embedded subtitle within a video in HLS direct mode? If I chose Any subtitle mode in Channel settings, it will also try to fallback to use ffmpeg profile to transcode.

Thanks!

**Comment by Domjen2521** [comment]
For HLS Direct, the files are just sent directly to the player. The embedding of subtitles has to be done during encoding. You would have to use one of the other options that allows transcoding in order for it to send the subs with it. have you attempted with hls segmented. im not sure if it will or will not work.

**Comment by jasongdove** [comment]
Subtitles in `HLS Direct` is limited by the container - `MPEG-TS`/`TS` is currently used and ONLY supports DVB subtitles. See https://en.wikipedia.org/wiki/Comparison_of_video_container_formats

On develop builds, I recently switched `HLS Direct` to use `MP4` container (the only other option within the HLS spec), which has a little better support for subtitles. For vobsub/dvd subtitles, they can now be stream copied with `HLS Direct`. Text subtitles will have to be transcoded, which kind of breaks the spirit of `HLS Direct` but that might be acceptable. I'll keep brainstorming.
