### ISSUE TITLE
New feature - Guide Request

### ISSUE THREAD

**Issue by gonecrazy25** [ErsatzTV/ErsatzTV#1158]
I just switched all my channels from dizqueTV to ErsatzTV mainly to take advantage of smart collections and hardware encoding and it is working really well.  The thing I miss about dizqueTV is the Guide page, it would be nice if there could be a guide web page added to ErsatzTV's web interface that would show the TV Guide with the logos, it makes it very easy to check what a schedule looks like at that point in time and if the logos look good without having to have another program up like plex or other iptv viewer.  I attached an example of the guide from dizquetv.
![Disquetv-guide-example](https://user-images.githubusercontent.com/9386188/218817220-01562235-dc57-4578-b914-69a27f0a3a98.JPG)

**Comment by boroborob** [comment]
Hi,
If you go to Playouts and click on one of the items then scroll down you will find the actual "guide" there, visually not that nice but it works. :)
Would be better if it was listed right under the playout you clicked on.

**Comment by jasongdove** [comment]
I don't plan on adding this feature to ErsatzTV at this time.

If you use chrome, this extension might be what you're looking for https://chromewebstore.google.com/detail/epg-viewer/lnhfllpjnichiepbkgnfhpaakhicbelh
