### ISSUE TITLE
Feature Request: Add Kodi InputStream properties to channels.m3u

### ISSUE THREAD

**Issue by Killface1980** [ErsatzTV/ErsatzTV#1204]
Thanks for this great application.

Kodi has a plugin for HLS streams in m3us called InputStream Adaptive.
According to https://forum.kodi.tv/showthread.php?tid=366536, the m3u would need some additional lines to get it working.
`#KODIPROP:inputstream=inputstream.adaptive`
`#KODIPROP:inputstream.adaptive.manifest_type=hls`
Would it be possible to add this feature?

**Comment by hartontw** [comment]
- **Hardware:** `Raspberry Pi 4 4Gb`
- **OS:** `LibreElec 10.0.4`
-  **Addon:** `PVR IPTV Simple Client 19.2.2.1`
    - Settings
      - Advanced
        - Inputstream name: `inputstream.ffmpegdirect`

Same result.

I can watch one channel, stop it and resume it, but if I change to another channel stops working.

**Comment by hartontw** [comment]
I've been able to get it working with those props:

```
#KODIPROP:inputstream=inputstream.ffmpegdirect
#KODIPROP:mimetype=application/x-mpegURL
#KODIPROP:inputstream.ffmpegdirect.open_mode=ffmpeg
``` 

<details><summary>Example:</summary>

```
#EXTM3U url-tvg="http://192.168.1.48:8409/iptv/xmltv.xml" x-tvg-url="http://192.168.1.48:8409/iptv/xmltv.xml"
#KODIPROP:inputstream=inputstream.ffmpegdirect
#KODIPROP:mimetype=application/x-mpegURL
#KODIPROP:inputstream.ffmpegdirect.open_mode=ffmpeg
#EXTINF:0 tvg-id="1.etv" channel-id="qGAEbqiTZ0-GRwlEZCo8Vg" channel-number="1" CUID="qGAEbqiTZ0-GRwlEZCo8Vg" tvg-chno="1" tvg-name="ErsatzTV" tvg-logo="http://192.168.1.48:8409/iptv/images/ersatztv-500.png" group-title="ErsatzTV" tvc-stream-vcodec="h264" tvc-stream-acodec="ac3", ErsatzTV
http://192.168.1.48:8409/iptv/channel/1.m3u8?mode=hls-direct
#KODIPROP:inputstream=inputstream.ffmpegdirect
#KODIPROP:mimetype=application/x-mpegURL
#KODIPROP:inputstream.ffmpegdirect.open_mode=ffmpeg
#EXTINF:0 tvg-id="2.etv" channel-id="Epv4pm2hqUWKZmata9mwig" channel-number="2" CUID="Epv4pm2hqUWKZmata9mwig" tvg-chno="2" tvg-name="Test" tvg-logo="http://192.168.1.48:8409/iptv/images/ersatztv-500.png" group-title="ErsatzTV" tvc-stream-vcodec="h264" tvc-stream-acodec="ac3", Test
http://192.168.1.48:8409/iptv/channel/2.m3u8?mode=hls-direct
``` 
</details>

**Comment by jasongdove** [comment]
I have added the `inputstream.ffmpegdirect` lines to develop builds. They will only be present for Kodi user agents, and will use the appropriate mime type based on the channels streaming mode (`application/x-mpegURL` is technically incorrect for HLS Direct, it should be `video/mp2t`).
