### ISSUE TITLE
Need guidance with music videos.

### ISSUE THREAD

**Issue by paul19920801** [ErsatzTV/ErsatzTV#1257]
Hi all. 

I'm just some guy who doesn't know what he's doing with setting Ersatz TV up for music videos. 

At the moment, it is working - I have my music videos stored as OtherVideos, and is a local library.  

However this setup isn't ideal, as I would like the artist, and track name, and the year the track was released to flash upon the song's intro. At the moment, I just have music videos playing constantly, which is essentially two thirds of what I require. 

I read something about NFO files being needed, and the music videos needing to be in seperate folders by artists. 

I've never dealt with this kind of thing before, and would need to know how would I generate the NFO files. Is there a program that's required?

 All the music videos are stored on a OneDrive account, and is linked via RClone, and the Ersatz TV server is a VPS machine. 
 
 I appreciate the feedback.
 
 Thanks in advance.

**Comment by paul19920801** [comment]
Any update?

**Comment by seamonkey420** [comment]
kodi would be easiest way to create nfos. however not all of my music videos are found via their scanner. also kodi exports the nfo as artist - title.nfo and not artist.nfo as ersatztv needs. afaik ersatztv needs it as artist.nfo to show in the guide (again i could br wrong on this)

yea i wish it would just read metadata from mp4/mkv files instead.

**Comment by paul19920801** [comment]
> kodi would be easiest way to create nfos. however not all of my music videos are found via their scanner. also kodi exports the nfo as artist - title.nfo and not artist.nfo as ersatztv needs. afaik ersatztv needs it as artist.nfo to show in the guide (again i could br wrong on this)
> 
> yea i wish it would just read metadata from mp4/mkv files instead.


I don't want video titles, and artists showing in the guide. I would rather keep the video titles a random shuffled suprise. Like on VH1.  I just want the song tiles displayed on the screem. One way of potentially doing it would be to hardcode the title to each video. With over 1000 videos (and counting) this is going to be hell, and time consuming to do.

**Comment by jasongdove** [comment]
If you want artist and track metadata without NFO files, you will need to use local music video libraries, not other video libraries. If you use one of the folder layouts described here, artist and track will populate

https://ersatztv.org/user-guide/local-libraries/#folder-layout_2

**Comment by paul19920801** [comment]
Just an update, I have added NFO files, readded the files as musicvideos. The artist and track has populated, but still don't see the artist and title of the music video display on my screen. Am I missing something?

**Comment by jasongdove** [comment]
There's a channel setting called `Music Video Credits Mode` that needs to be set to `Generate Subtitles`.
