### ISSUE TITLE
Option to bypass TLS verification to MediaServer

### ISSUE THREAD

**Issue by Roxedus** [ErsatzTV/ErsatzTV#1268]
My plex is set to prefer secure connections, this means that plex responds with a https address as the first address. This connection is using the plex-generated certificate, which by nature is not trusted on this IP. 

My request is twofold, an option to not validate ssl certificates for connections to media server, and the ability to specify the address ourself.

**Comment by jasongdove** [comment]
ETV will try all advertised addresses to find one that works. You should add the address you would like to use to Plex's Settings > Network >  Custom server access URLs. After saving those changes, restart ETV and it should update it's list from Plex's API and try each address again. It might also be worth enabling debug logs in ETV's Settings page before doing this so you can see each address that is attempted.

**Comment by Roxedus** [comment]
I am aware this is how it is done, thus why the mismatched certificate is a thing. I only have a https endpoint listed as a local LAN  Custom URL, which is not a issue for anything else communicating to plex outside of the docker network.

**Comment by jasongdove** [comment]
> plex responds with a https address as the first address

The addresses are effectively unordered; ETV will try every address that Plex sends until it finds one that succeeds.

> the ability to specify the address ourself

This will not be added to ETV when Plex contains an official way to advertise additional addresses.

> an option to not validate ssl certificates for connections to media server

This shouldn't be needed - why are the Plex certificates not trusted? Have you configured DNS rebinding so the plex.direct addresses can succeed?

If you enable debug logs as I suggested you will see all addresses that ETV tries to use; you can also query the database directly with `sqlite3 ersatztv.sqlite3 'select Uri from PlexConnection'`.

**Comment by Roxedus** [comment]
I have no plex.direct in my connection strings. ETV also wasn't happy with the connection it tried to established to my domain (which is overridden in dns to take the direct route, to a valid certificate). The plex clients have no issues with the connections strings.

**Comment by jasongdove** [comment]
I'm happy to help troubleshoot when you provide the output of the following command (run in ETV's config folder):

```shell
sqlite3 ersatztv.sqlite3 'select Uri from PlexConnection'
```

Change the hostnames if you desire, but please leave schema, port, private ips, etc intact.

**Comment by Roxedus** [comment]
I do plan to come back to this, I just dont have any logs to give atm
