### ISSUE TITLE
[Feature Request] add suport for frame rade and more resolution to the ffmpeg profile settings

### ISSUE THREAD

**Issue by www2000** [ErsatzTV/ErsatzTV#1291]
Hi i like to see that there add support for more resolution than the current ones.
And like that the following resolutions will be add 768 × 576 and 720 × 576 (pal/secam).
Beside this i like also to have a option that i can force a channel to play in a specifide frameraide as:
24p (23.976 FPS Movies)
25p (25 FPS PAL/SECAM)
30p  (~29,97 FPS NTSC)
50p (50 FPS PAL/SECAM)
59.94p (~59,94 FPS NTSC)
and 60p (60 FPS HFR Movies)

Beside this i like to see that be an option to be add that force a aspect ratio to the channel with the foaling options:
ALL
4:3
16:9

more info:
https://gist.github.com/jonlabelle/7834592 list with common Resolutions
https://en.wikipedia.org/wiki/List_of_films_with_high_frame_rates 
https://en.wikipedia.org/wiki/Display_aspect_ratio

**Comment by jasongdove** [comment]
Custom resolution management is now available on develop builds/tags, and will be included in the next release.
