### ISSUE TITLE
Cannot display properly in 4:3

### ISSUE THREAD

**Issue by GreenTeaBD** [ErsatzTV/ErsatzTV#1332]
Tested in both Chrome and Firefox on Debian and Windows 11 in Firefox. Using Jellyfin.

The problem is basically that the "fill" option for aspect ratio in Jellyfin will not stretch out 4:3 content to cover the whole screen, and on a 4:3 screen none of the options will actually fill the screen, the content will be squished even with 4:3 content on a 4:3 screen.

I think this has something to do with transcoding, at least that was my first thought, I switched some of the channels to HLS-Direct though as it says it doesn't support transcoding but that didn't seem to make a difference.

But it looks like it assumes 16:9, and none of the resolution options under ffmpeg profiles are 4:3 except 640x480, but I'm not sure. Playing the same content from jellyfin and selecting fill, and it will fill, but then from the channel it just wont.

Setting it to 640x480 does work. Which makes me wonder if me setting things to HLS-Direct for some reason didn't work. But, yeah maybe this would be solved by having some more but not so low 4:3 resolutions. Or, probably even more ideally, it someone could tell me if there is just a file somewhere to manually change the target resolution for ffmpeg?

**Comment by jasongdove** [comment]
The next release will allow you to define custom resolutions in the main `Settings` page. If you want to try it now, it's available on develop builds. Docker tags would use `develop` instead of `latest` and other builds are always available here https://github.com/jasongdove/ErsatzTV/releases/tag/develop

**Comment by jasongdove** [comment]
Custom resolutions have been available in releases for a while now.
