### ISSUE TITLE
[Feature Request] Possibility to add Music Video playlist(s) to a new collection?

### ISSUE THREAD

**Issue by SplitEnz** [ErsatzTV/ErsatzTV#1333]
I've created several Music Video playlists in Emby for the 80's / 90's / 00's etc which displays the title of the playlist, an overview description for the entire playlist, the duration for the entire playlist and all of the genres that are included in the playlist.
I've been trying to think how I might be able to replicate the above format, so that all the videos in a particular playlist would represent one single item in a collection? The idea being, that if I could add multiple music video playlists to a collection, I could then create a new channel made up of just Music Video's with multiple programmes based on the playlist title, the playlist overview description and playlist duration. Just to be clear, I'm not wanting the TV guide to show each individual music video title and duration.
Is this something that might be doable? 
If not, maybe somebody could give some guidance on how I might best tackle this in order to achieve what I'm looking to do.   
Apologies in advance if such a request has been requested/asked previously.

**Comment by SplitEnz** [comment]
Jason
Feel free to close this request. 
I actually ended up hacking my way to a reasonably simple solution by joining several music videos together to form a single video file. By naming this file as the programme title I want to see in the TV guide and creating a NFO with the programme plot details and then adding to a new music video collection, I'm able to use with a TV channel dedicated to just music videos. All I have to do is repeat the process for other programmes, then add these to the same collection. 

It's all working like a charm and just how I had originally envisaged!
Thought I would post an update, as this might be useful to other people who were wanting to achieve the same effect.

The only real downside is each programme title created from the joined music videos will always have the same playback order. Also, I'm not able to show Artist/Album/Year, unless I hardcode that info onto each video, prior to joining them together.

However, one small snag I have is how to add poster art for these music videos. I couldn't find anything in the documentation on how to add artwork for a specific music video. Should I just add my poster artwork to the music video folder? Is there any specific naming convention I should use? Or do I simply add a tag to the NFO file with the associated file path for the artwork? I have tried various things, but artwork is still not being picked up at the moment. Grateful if you could advise on the correct process.
I also noticed that if the character '&' is used on the plot tag within the NFO, then the entire plot description will not be added. I only picked on this when I had the music artist Womack & Womack mentioned in one of my plot descriptions.  
Cheers

**Comment by KINGLIFER** [comment]
OMG that isn't acceptable. I tried asking on the discord but man those guys were assholes over there. Nice at first.... I was hoping you had a solution.
