### ISSUE TITLE
amdgpu (VAAPI RadeonSI) error with 2 or more playouts/channels

### ISSUE THREAD

**Issue by botrosco** [ErsatzTV/ErsatzTV#1350]
When running 2 or more streams i get the following error while using hardware accel (VAAPI RadeonSI)
`amdgpu os_same_file_description couldnt determine if two DMS fds reference the same file description`
Full error shown in the playback in jellyfin:
![image](https://github.com/jasongdove/ErsatzTV/assets/51170107/f8a34d90-195d-4499-8894-a5ade6a80f55)
Error shown in logs:
`HLS process for channel 1 has terminated unsuccessfully with exit code 1: amdgpu: os_same_file_description couldn't determine if two DRM fds reference the same file description.`

Setup:
OS: Ubuntu 22.04.2 LTS
Docker: v20.10.21
ErsatzTV Version: 0.8.0-2ad27c2b-docker-vaapi (Tested latest vaapi in both staging and dev)
VAINFO:
`vainfo: VA-API version: 1.18 (libva 2.18.0)
vainfo: Driver version: Mesa Gallium driver 23.2.0-devel for AMD Radeon R9 380 Series (tonga, LLVM 13.0.1, DRM 3.42, 5.15.0-78-generic)`

Im then required to reboot the system to get it to 'unblock' the card to be able to run any streams again with a single stream. as soon as a stream is watched while 2 are available the error returns.

Thanks

**Comment by irfanhakim-as** [comment]
I'm getting this now, even with 1 single channel, and 1 single streaming session/attempt. May I know what could be the cause of this?

```
HLS process for channel 101 has terminated unsuccessfully with exit code 137: amdgpu: os_same_file_description couldn't determine if two DRM fds reference the same file description.
```
