### ISSUE TITLE
Different audio tracks. 

### ISSUE THREAD

**Issue by paul19920801** [ErsatzTV/ErsatzTV#1381]
Hi. Having an issue with some files with dual English/russian audio. 

I'm a native English speaker, and therefore would obviously want the English track to play by default. But with a small amount of files, I get Russian audio. Not English. 

Is there a way to have the option to select from multiple soundtracks for playback? Or at least have the ability to choose the default soundtrack?

Not sure if that's something to be done in Plex, or ErsatzTV, or if I manually need to edit the file to remove the russian audio. 

Thanks

**Comment by winstonrc** [comment]
This is particularly noticeable on anime with English and Japanese audio tracks and subtitles. For some anime, I prefer it with the Japanese audio and English subtitles, but for others I want it with just the English audio and no subtitles. If it were possible to set it on a case-by-case basis, that would be miraculous.
