### ISSUE TITLE
Random restart of program show

### ISSUE THREAD

**Issue by Domjen2521** [ErsatzTV/ErsatzTV#1409]
The show randomly restarts from the beginning after about 2 to 3 minutes. The show will play fine then randomly begin again. This has happened randomly on many channels and shows. I am running HLS Segmenter on all channels. I cant seem to narrow down the issue. i just wanted to let know whats going on. The current version im on is v0.8.1-8b0b927a-win-x64 but it also occurred on the previous version. i am going to attempt to see if i cant catch the exact time and error for the logs.

**Comment by jasongdove** [comment]
I believe this bug existed for a day or so while this feature was added/stabilized

> - Optimize transcoding session to only work ahead (at max speed) for 2 minutes before throttling to realtime
>   - This should *greatly* reduce cpu/gpu use when joining a channel, particularly with long content

The affected commits were probably

8f241f49fca9ac4a7b284025b047ce83812e0a64
efc710749e063b1c11ce364d31204aedaead3b10
0a7513622348a93721612703ecd901842dd35295
cb43c28d00f7bff43048c6dea60b9a55b30985fc

The bug should no longer be present with version 225b95449c53bcd0070b8e8c58f3bd2cbd516aa2 and newer (this includes the 8b0b927a version you are on now).

Are you able to confirm which version you were on previously? Also let me know if you do see the behavior again on the latest version.

**Comment by Domjen2521** [comment]
@jasongdove The issue is still present on version 8b0b927. It occurred this morning. here is the log below. Let me know if there is anything i can do to assist.

<html><body>


9/2/2023 9:14:34 AM -05:00 | Information | ffmpeg hls  arguments -threads 1 -nostdin -hide_banner -nostats -loglevel error  -fflags +genpts+discardcorrupt+igndts -hwaccel cuda -c:v h264_cuvid  -hwaccel_output_format cuda -re -i "\\MINGOSERVER\Media\TV Shows\The  Looney Tunes Show\Season 01\S01e22 - Beauty School.mkv" -filter_complex  [0:1]loudnorm=I=-16:TP=-1.5:LRA=11,apad=whole_dur=1355788.5952ms[a];[0:0]scale_cuda=1920:1080:format=nv12:force_original_aspect_ratio=decrease,setsar=1,hwdownload,format=nv12,pad=1920:1080:-1:-1:color=black[v];[v]setparams=range=tv:colorspace=bt709:color_trc=bt709:color_primaries=bt709[vpf]  -map [a] -map [vpf] -muxdelay 0 -muxpreload 0 -movflags +faststart  -flags cgop -sc_threshold 0 -t 00:22:35.7885952 -video_track_timescale  90000 -b:v 2000k -maxrate:v 2000k -bufsize:v 4000k -c:v h264_nvenc  -pix_fmt yuv420p -output_ts_offset 889.5970222222222 -c:a aac -b:a 192k  -maxrate:a 192k -bufsize:a 384k -ar 48k -map_metadata -1 -metadata  "service_provider=\"ErsatzTV\"" -metadata "service_name=\"Cartoon  Network\"" -g 96 -keyint_min 96 -force_key_frames expr:gte(t,n_forced*4)  -f hls -hls_time 4 -hls_list_size 0 -segment_list_flags +live  -hls_segment_filename "C:\Users\Mingo  Arcade\AppData\Local\etv-transcode\19\live%06d.ts" -hls_flags  program_date_time+append_list+discont_start+omit_endlist+independent_segments  -mpegts_flags +initial_discontinuity "C:\Users\Mingo  Arcade\AppData\Local\etv-transcode\19\live.m3u8"
-- | -- | --
9/2/2023 9:14:34 AM -05:00 | Information | Forcing 1 ffmpeg thread when hardware acceleration is used
9/2/2023 9:14:34 AM -05:00 | Information | HLS session state: "ZeroAndRealtime"


</body>
</html>

<html><body>


  |  
-- | --



</body>
</html>

**Comment by jasongdove** [comment]
Please set your log level to `Debug` in ETV's main settings page. When it happens again, please paste today's log file somewhere, or send it in a private message on Discord. I think the debug logs will be needed in this case.

The daily log files are locate in ETV's config folder / logs subfolder.

**Comment by Domjen2521** [comment]
After running it for a while, it was not happening again. i saw today that you released another update. i have moved to v0.8.1-b1cd324f-win-x64. I have kept debug active, I will keep checking today to see if it occurs.

**Comment by Domjen2521** [comment]
Today one of my shows was stuck in roughly a 2 minute loop. it was on this for quite some time. I hope the log info helps. it occurred with the show Hogans Heroes roughly at about 15:42 or so.

[ersatztv20230905.log](https://github.com/ErsatzTV/ErsatzTV/files/12528692/ersatztv20230905.log)

**Comment by Domjen2521** [comment]
date 09-06-23 at about 16:50 today the system was doing the loop on another channel. this one is a tom and jerry channel. still cant figure out where its coming from exactly. here is the log file. 
[ersatztv20230906.log](https://github.com/ErsatzTV/ErsatzTV/files/12542853/ersatztv20230906.log)

**Comment by Domjen2521** [comment]
secondary part of previous post -this one occurred as i was pasting the first one.

<html><body>


9/6/2023 5:31:59 PM -05:00 | Information | ffmpeg hls  arguments -threads 1 -nostdin -hide_banner -nostats -loglevel error  -fflags +genpts+discardcorrupt+igndts -hwaccel cuda -c:v h264_cuvid  -hwaccel_output_format cuda -i "\\MINGOSERVER\Media\TV Shows\The Golden  Girls\Season 05\S05e15 - Triple Play.mkv" -filter_complex  [0:1]loudnorm=I=-16:TP=-1.5:LRA=11,apad=whole_dur=120000ms[a];[0:0]scale_cuda=1920:1080:format=nv12:force_original_aspect_ratio=decrease,setsar=1,hwdownload,format=nv12,pad=1920:1080:-1:-1:color=black[v];[v]colorspace=irange=tv:ispace=smpte170m:itrc=bt709:iprimaries=smpte170m:all=bt709:format=yuv420p[vpf]  -map [a] -map [vpf] -muxdelay 0 -muxpreload 0 -movflags +faststart  -flags cgop -sc_threshold 0 -t 00:02:00 -video_track_timescale 90000  -b:v 2000k -maxrate:v 2000k -bufsize:v 4000k -c:v h264_nvenc  -output_ts_offset 2989.7534333333333 -c:a aac -b:a 192k -maxrate:a 192k  -bufsize:a 384k -ar 48k -map_metadata -1 -metadata  "service_provider=\"ErsatzTV\"" -metadata "service_name=\"The Golden  Girls\"" -g 96 -keyint_min 96 -force_key_frames expr:gte(t,n_forced*4)  -f hls -hls_time 4 -hls_list_size 0 -segment_list_flags +live  -hls_segment_filename "C:\Users\Mingo  Arcade\AppData\Local\etv-transcode\91\live%06d.ts" -hls_flags  program_date_time+append_list+discont_start+omit_endlist+independent_segments  -mpegts_flags +initial_discontinuity "C:\Users\Mingo  Arcade\AppData\Local\etv-transcode\91\live.m3u8"
-- | -- | --
9/6/2023 5:31:59 PM -05:00 | Information | Forcing 1 ffmpeg thread when hardware acceleration is used
9/6/2023 5:31:59 PM -05:00 | Debug | FFmpeg  pipeline  ["ThreadCountOption","NoStandardInputOption","HideBannerOption","NoStatsOption","LoglevelErrorOption","StandardFormatFlags","NoDemuxDecodeDelayOutputOption","FastStartOutputOption","ClosedGopOutputOption","NoSceneDetectOutputOption","TimeLimitOutputOption","CudaHardwareAccelerationOption","VideoTrackTimescaleOutputOption","VideoBitrateOutputOption","VideoBufferSizeOutputOption","EncoderH264Nvenc","OutputTsOffsetOption","EncoderAac","AudioChannelsOutputOption","AudioBitrateOutputOption","AudioBufferSizeOutputOption","AudioSampleRateOutputOption","DoNotMapMetadataOutputOption","MetadataServiceProviderOutputOption","MetadataServiceNameOutputOption","OutputFormatHls","ComplexFilter"],  ["NormalizeLoudnessFilter","AudioPadFilter"],  ["ScaleCudaFilter","PadFilter","EncoderH264Nvenc"]
9/6/2023 5:31:59 PM -05:00 | Debug | Checking for JS Script at C:\Users\Mingo Arcade\AppData\Local\ersatztv\scripts\audio-stream-selector\episode.js
9/6/2023 5:31:59 PM -05:00 | Debug | Unable to locate episode audio stream selector script; falling back to built-in logic
9/6/2023 5:31:59 PM -05:00 | Debug | SelectAudioStream duration: "00:00:00.0001020"
9/6/2023 5:31:59 PM -05:00 | Debug | Unable to find audio stream with preferred audio language code(s) ["eng"]
9/6/2023 5:31:59 PM -05:00 | Debug | Found audio stream flagged as default
9/6/2023 5:31:59 PM -05:00 | Debug | FFmpeg  desired state FrameState { Realtime = False, InfiniteLoop = False,  VideoFormat = h264, VideoProfile = Some(main), PixelFormat =  Some(ErsatzTV.FFmpeg.Format.PixelFormatYuv420P), ScaledSize = FrameSize {  Width = 1600, Height = 1080 }, PaddedSize = FrameSize { Width = 1920,  Height = 1080 }, IsAnamorphic = False, FrameRate = None, VideoBitrate =  Some(2000), VideoBufferSize = Some(4000), VideoTrackTimeScale =  Some(90000), Deinterlaced = False, FrameDataLocation = Unknown,  FFmpegAspectRatio = 16/9, BitDepth = 8 }
9/6/2023 5:31:59 PM -05:00 | Debug | Channel 91 has no preferred audio language code
9/6/2023 5:31:59 PM -05:00 | Information | HLS session state: "ZeroAndRealtime"


</body>
</html>

**Comment by jasongdove** [comment]
Thanks for the additional details. The issue appears to happen when the HLS Segmenter decides that it needs to work ahead again (after the channel has already been transcoding, but has fallen behind realtime/the wall clock).

Please update and try the fix in version a90348740d574d960a6cd5961cfc477100ddaba5

**Comment by Domjen2521** [comment]
test for a few hours issue resolved. with a903487
