### ISSUE TITLE
[Feature Request] Second Audio Track for Channels

### ISSUE THREAD

**Issue by notpointify** [ErsatzTV/ErsatzTV#1421]
### Feature request
Currently ErsatzTV channels only support streaming **one** audio track. I'm not sure how plausible this would be, but it would be nice to be able to have a second audio track for each channel, not unlike SAP (Second Audio Program) on regular TV channels.

### Examples of how SAP is used on TV
* Free-to-air TV channels usually use SAP for audio description, for the visually impaired.
* In USA, some programs on cable TV use SAP for Spanish-language audio, and in rare cases Spanish-language programs use SAP for English-language audio.
* In Canada, SAP is used by some channels to provide French-language audio.
* In my country (Argentina) and other non-English speaking countries where Hollywood movies and other foreign programs are dubbed on TV, cable channels tend to use SAP for the original language audio.

**Comment by rafaelvieiras** [comment]
Do you know of any IPTV player with this feature? To select a second audio! I don't know of any IPTV client with audio track selection. (I'm using Android TV to watch)

But, I understand your idea, I'm from Brazil and here the TV puts the original audio of the film on a second track, or vice versa.

I have many movies and TV shows with dual audio, and I would love to have this ability to change the audio track on IPTV.

**Comment by Znuff** [comment]
Almost every IPTV player I've seen supports dual-language streams, as most are using ExoPlayer or LibVLC under the hood.

If you want something to test, then you can use tivimate.
