### ISSUE TITLE
[Feature Request] Allow 4:3 cropping, especially with NVENC

### ISSUE THREAD

**Issue by dude22072** [ErsatzTV/ErsatzTV#1424]
Many old 4:3 shows are released today with black bars added to the side to pad them out to 16:9 resolutions without stretching them. Unfortunately this has the side effect that when viewed on a 4:3 screen they are shrunk unless you crop out the black bars. Having the ability to crop certain content would be nice as the alternative is telling the video player to crop everything to 4:3, however this would also crop actual 16:9 content as well.

With software encoding this should be as simple as adding `crop=iw/4*3:ih` early on in the video filters chain.
With NVENC the crop filter is unfortunately not supported, instead needing to be passed as a decoder option with absolute pixels (see nVidia's documentation: https://docs.nvidia.com/video-technologies/video-codec-sdk/12.0/ffmpeg-with-nvidia-gpu/index.html#hwaccel-transcode-with-scaling). So for instance, to crop a 1920x1080 video to 4:3, you would need to pass the option `-crop 0x0x240x240` before the input.

**Comment by jasongdove** [comment]
A simple crop feature is now available for testing on develop builds/tags. It's a new option for `Scaling Behavior` in the ffmpeg profile.

Note that it does not detect black, so it will also crop 16:9 content as you describe.

**Comment by dude22072** [comment]
Sorry for taking so long to get back to this, but there are several issues with cropping currently. Using NVENC with the preferred resolution set to 640x480 and the Scaling Behavior set to crop, a 1920x1080 video file (4:3 padded out with black bars) is being streamed at 854x480 and still has black bars. The channel logo watermark is even out in the black bar area:
![vlcsnap-2024-01-08-19h16m14s535](https://github.com/ErsatzTV/ErsatzTV/assets/4349800/0f19b893-634a-4e06-93f7-cf52b91861aa)
it's not simply a logo issue as setting the watermark to be within the content the resolution and black bar issues persist:
![vlcsnap-2024-01-08-19h17m44s931](https://github.com/ErsatzTV/ErsatzTV/assets/4349800/a04405fd-a7d5-4d5e-aa7d-24e5471ba0ce)
turning off NVENC the stream is properly 640x480, however with the logo watermark set to be within the content it's nearly in the middle of the screen:
![vlcsnap-2024-01-08-19h23m05s123](https://github.com/ErsatzTV/ErsatzTV/assets/4349800/536e7f0c-4041-41d4-8260-f9f7cf0dbf96)
in all instances the watermark is set to the default 15% width/5% margins.

**Comment by dude22072** [comment]
After a little more testing, it appears that all 16:9 content is not being cropped to 4:3 on 640x480 with NVENC, only software encoding, including 16:9 480p content.

**Comment by jasongdove** [comment]
Whoops, looks like I missed NVIDIA. Should be fixed on develop builds now with #1545

**Comment by ankitnaik1** [comment]
Looks like you missed quicksync as well

**Comment by jasongdove** [comment]
@ankitnaik1 thanks - QSV was fixed with #1546

**Comment by wdstudios2** [comment]
This reminds me... It would be great if individual schedule items had their own transcoding setting overrides. My channels mix a lot of stuff from a lot of different sources and it all needs to be handled differently. For example, my 352x240 videos need to be stretched and warped to fit 4:3, but the pillarboxed widescreen BS needs to be cropped.
