### ISSUE TITLE
Sync schedule between multiple playouts

### ISSUE THREAD

**Issue by arthuraltino** [ErsatzTV/ErsatzTV#1460]
Is it possible to have the exactly same schedule running in two or more playouts? I've achieved this buy setting playback order as chronological or shuffle in order, but it doesn't seem to be possible when using shuffle or random playback order. I'm trying to set two channels: one with english audio and portuguese subtitles and another one with portuguese audio and no subtitles. I'd like them to simulcast the same shuffled content, is it possible?

**Comment by Moonbase59** [comment]
I’d also be interested in that. Family watches in German, I watch in English, so the logical approach would be 2 channels (or, better, sending multiple audio streams like "real" TV stations do, and having clients that can select which to play!)
