### ISSUE TITLE
Subtitles not working from Plex Media

### ISSUE THREAD

**Issue by Ay1tsMe** [ErsatzTV/ErsatzTV#1470]
Unless I've configured it wrong, I'm unable to view subtitles from my shows when I configured the schedule and the channel to prefer English subtitles. Linked below is my settings I've put for my schedules and channel:
![image](https://github.com/ErsatzTV/ErsatzTV/assets/110982014/3d91e210-c8b3-48fc-a739-124029377fb4)
![image](https://github.com/ErsatzTV/ErsatzTV/assets/110982014/4974e9c9-7cae-484c-a30a-149fe2f107af)

On plex, i can select the subtitles so they are there, I just don't know how to select it so that Ersatz shows subtitles by default for this channel

**Comment by Znuff** [comment]
This issue should be re-tested, as there have been numerous improvements in the latest `dev` builds for subtitle extraction.

**Comment by c0pper** [comment]
Hi, I just started playing today with ETV, and I'm also finding it hard to display subtitles. Any new development or things I should be aware of regarding this issue?
