### ISSUE TITLE
Search for language doesn’t work

### ISSUE THREAD

**Issue by Moonbase59** [ErsatzTV/ErsatzTV#1472]
Running ~~0.8.2-5291832e-docker-vaapi~~ 0.8.2-c3fe2639-docker-vaapi and trying to search for movies/episodes in certain languages:

```
language:eng
```

All my videos have the language(s) tagged, and the [doc](https://ersatztv.org/docs/user-guide/search#movies) says "`language:` The movie audio stream language".

All I get is an empty results page.

Searching for other language variants like `de`, `deu` or `ger` also has zero results.

Just for proof, here is the data for a random movie (The Pink Panther):

```json
{
  "Id": 2613,
  "Kind": "JellyfinMovie",
  "LibraryKind": "JellyfinLibrary",
  "ServerName": "media",
  "LibraryName": "Filme",
  "State": "RemoteOnly",
  "Duration": "01:50:23.4799999",
  "SampleAspectRatio": "0:0",
  "DisplayAspectRatio": "16:9",
  "RFrameRate": "25.00",
  "VideoScanKind": "Interlaced",
  "Width": 720,
  "Height": 576,
  "Streams": [
    {
      "Index": 0,
      "Kind": "Video",
      "Codec": "mpeg2video",
      "Profile": "main",
      "Language": "eng",
      "Default": true,
      "PixelFormat": "yuv420p",
      "ColorRange": "",
      "ColorSpace": "",
      "ColorTransfer": "",
      "ColorPrimaries": ""
    },
    {
      "Index": 1,
      "Kind": "Audio",
      "Title": "English DD 5.1",
      "Codec": "ac3",
      "Profile": "",
      "Language": "eng",
      "Channels": 6,
      "Default": true
    },
    {
      "Index": 2,
      "Kind": "Audio",
      "Title": "Deutsch DD 5.1",
      "Codec": "ac3",
      "Profile": "",
      "Language": "ger",
      "Channels": 6
    },
    {
      "Index": 3,
      "Kind": "Audio",
      "Title": "French DD 5.1",
      "Codec": "ac3",
      "Profile": "",
      "Language": "fre",
      "Channels": 6
    },
    {
      "Index": 4,
      "Kind": "Audio",
      "Title": "Italian DD 2.0",
      "Codec": "ac3",
      "Profile": "",
      "Language": "ita",
      "Channels": 2
    },
    {
      "Index": 5,
      "Kind": "Audio",
      "Title": "Spanish DD 2.0",
      "Codec": "ac3",
      "Profile": "",
      "Language": "spa",
      "Channels": 2
    },
    {
      "Index": 6,
      "Kind": "Audio",
      "Title": "Czech DD 2.0",
      "Codec": "ac3",
      "Profile": "",
      "Language": "cze",
      "Channels": 2
    },
    {
      "Index": 7,
      "Kind": "Audio",
      "Title": "English Commentary Blake Edwards (director)",
      "Codec": "ac3",
      "Profile": "",
      "Language": "eng",
      "Channels": 2
    },
    {
      "Index": 8,
      "Kind": "Subtitle",
      "Codec": "dvdsub",
      "Language": "eng"
    },
    {
      "Index": 9,
      "Kind": "Subtitle",
      "Codec": "dvdsub",
      "Language": "ger"
    },
    {
      "Index": 10,
      "Kind": "Subtitle",
      "Codec": "dvdsub",
      "Language": "fre"
    },
    {
      "Index": 11,
      "Kind": "Subtitle",
      "Codec": "dvdsub",
      "Language": "ita"
    },
    {
      "Index": 12,
      "Kind": "Subtitle",
      "Codec": "dvdsub",
      "Language": "spa"
    },
    {
      "Index": 13,
      "Kind": "Subtitle",
      "Codec": "dvdsub",
      "Language": "dut"
    },
    {
      "Index": 14,
      "Kind": "Subtitle",
      "Codec": "dvdsub",
      "Language": "swe"
    },
    {
      "Index": 15,
      "Kind": "Subtitle",
      "Codec": "dvdsub",
      "Language": "fin"
    },
    {
      "Index": 16,
      "Kind": "Subtitle",
      "Codec": "dvdsub",
      "Language": "nor"
    },
    {
      "Index": 17,
      "Kind": "Subtitle",
      "Codec": "dvdsub",
      "Language": "dan"
    },
    {
      "Index": 18,
      "Kind": "Subtitle",
      "Codec": "dvdsub",
      "Language": "por"
    },
    {
      "Index": 19,
      "Kind": "Subtitle",
      "Codec": "dvdsub",
      "Language": "gre"
    },
    {
      "Index": 20,
      "Kind": "Subtitle",
      "Codec": "dvdsub",
      "Language": "tur"
    },
    {
      "Index": 21,
      "Kind": "Subtitle",
      "Codec": "dvdsub",
      "Language": "cze"
    },
    {
      "Index": 22,
      "Kind": "Subtitle",
      "Codec": "dvdsub",
      "Language": "eng"
    },
    {
      "Index": 23,
      "Kind": "Subtitle",
      "Codec": "dvdsub",
      "Language": "ger"
    },
    {
      "Index": 24,
      "Kind": "Subtitle",
      "Codec": "dvdsub",
      "Language": "fre"
    },
    {
      "Index": 25,
      "Kind": "Subtitle",
      "Codec": "dvdsub",
      "Language": "ita"
    },
    {
      "Index": 26,
      "Kind": "Subtitle",
      "Codec": "dvdsub",
      "Language": "spa"
    },
    {
      "Index": 27,
      "Kind": "Subtitle",
      "Codec": "dvdsub",
      "Language": "dut"
    },
    {
      "Index": 28,
      "Kind": "Subtitle",
      "Codec": "dvdsub",
      "Language": "eng"
    }
  ]
}
```

(Index 22 and up subtitles _appear_ duplicates but are actually the subtitles for the audio commentary track at index 7. Unfortunately, ETV doesn’t (yet?) evaluate "commentary", "original language", "hearing impaired" or "visual impaired" tags, so it is not shown in media info.) The "title" (description) of the subtitles is also not shown, it would have a textual description like "English Commentary Blake Edwards (director)", which I put there for software that doesn’t handle the tags. Media container is MKV, of course.

**Comment by jasongdove** [comment]
Most of the metadata displayed on etv details pages are clickable for searching, including language. The distinction here is that searches use English language names, not tagged values.

**Comment by Moonbase59** [comment]
Hm, what are you trying to say? I should use something like "German" or "English"? And are these always the _English_ names? (I wouldn’t be able to type Russian or Chinese, for instance.)

**Comment by jasongdove** [comment]
Search for a movie in etv, click on the poster to see the details, then click on a language from that page. It will take you to a search for all items with that language.

**Comment by Moonbase59** [comment]
Yeah, fantastic, that works! Thanks!

![ErsatzTV – Mozilla Firefox_004](https://github.com/ErsatzTV/ErsatzTV/assets/3706922/289d672a-e629-40ec-88da-287fcbac5a1a)

**Comment by Moonbase59** [comment]
@jasongdove It actually shows the language only on show seasons, neither on movies nor episodes.

Here is the page for "The Pink Panther" from above:

![grafik](https://github.com/ErsatzTV/ErsatzTV/assets/3706922/9d38368f-1d03-4ed1-9476-71b930dcc4b4)

**Comment by Moonbase59** [comment]
Possible **bug**: If a show has more than one language, the language isn’t shown anymore, not even on the show page!

Most of my videos have more than one language (I usually rip _all_ audio and subtitle tracks). The Pink Panther movie has several, but the Pink Panther _show_ I only have in English.

**Comment by jasongdove** [comment]
To be clear, searching for languages is not broken and works correctly in the latest release builds (and develop builds). I pointed you to the pages in the UI to clarify what I meant by "English language names" - that is, the UI displays the names as they are indexed.

With that said, you are correct that the language display for items with more than one language was broken. Good catch! This bug should now be fixed in the latest develop build with #1474.

**Comment by Moonbase59** [comment]
Yep, we are in agreement: Not broken, but not much documentation, so I assumed one has to input language codes instead of (English) language _names_.

In 0.8.2-17bed524-docker-vaapi, language is now shown for movies and shows. Can we expect this also for _episodes_?

Reason being: You might have bought a series/season on DVD/Blu-Ray that has episodes that never aired in your country, and thus are not dubbed. Would be nice to be able to spot these in an episode list.

**Comment by Moonbase59** [comment]
Sometimes difficult adding yet another translation layer in your head. How do I search for:

- zxx (tried: instrumental, "no linguistic content", none)
- mul (tried: multiple, "multiple languages")
- und (tried: undetermined, undefined, unknown
- no language tagged (tried: "", none, empty)

And yes, of course there _is_ media tagged like that.

**Comment by jasongdove** [comment]
The latest develop build updates the search index to include `language_tag` which is the raw value from the metadata, excluding null/empty values.

The syntax to search for an item that is indexed without this particular field is: `NOT _exists_:language_tag`.

**Comment by Moonbase59** [comment]
Wow, that’s a good enhancement, thanks! I’m now on `0.8.2-714f68a8-docker-vaapi` and searching existing tags works fine.

`_exists_` seems to return zero results in both these searches, though:

```
NOT _exists_:language_tag
_exists_:language_tag
```

**Comment by jasongdove** [comment]
No, you don't have to rescan for it to work. Are you combining those searches with something else? I can copy and paste those lines individually into the search box in ETV and get results.

Deep scan will ignore etag checks (which are used to quickly ignore unchanged items in a library) and scan all items, even those that haven't changed. It's mostly there to work around any potential etag bugs; if you find that you need to use deep scan to detect changes in a library it would be considered a bug.

**Comment by Moonbase59** [comment]
Thanks for the explanation!

You’re right: I don’t have Elasticsearch enabled. What would be the advantage, and would we lose Lucene syntax when doing that?

**Comment by jasongdove** [comment]
It's just one more service to maintain. I added it to see if it would be more performant than Lucene, but it hasn't been for me.

It's supposed to use the same Lucene syntax; I hadn't realized Elasticsearch extended it with some custom capabilities.

**Comment by Moonbase59** [comment]
I _think_ I found a solution using pure Lucene:

Search for existing `language_tag`:
```
language_tag:*
```

Search for movies that have _no_ `language_tag` (must use something before `NOT` because a query can’t start with `NOT`):
```
type:movie NOT language_tag:*
```

Using this, I actually found 29 movies in my collection where I forgot to tag the language!

Could you please verify that this is correct and works? If so, we can close this issue, hooray!

**Comment by jasongdove** [comment]
Good find, `NOT language_tag:*` gives the same results as `NOT _exists_:language_tag` on my system, and it works with Lucene, as you describe. Even `type:* NOT language_tag:*`.

**Comment by Moonbase59** [comment]
Great, thanks for checking. Another one solved :-)
