### ISSUE TITLE
Playout screen shows wrong default schedule (but playout is correct)

### ISSUE THREAD

**Issue by Moonbase59** [ErsatzTV/ErsatzTV#1482]
I’m on `0.8.2-714f68a8-docker-vaapi`. When checking "Playout", the wrong default schedule is shown (shows the alternate):

![Screenshot 2023-10-12 at 15-02-25 ErsatzTV](https://github.com/ErsatzTV/ErsatzTV/assets/3706922/deb92f50-8c1d-4d0b-8aa9-ed294ab5814e)

When clicking on the default schedule line, the actual (correct, from the other schedule) Playout Details are shown. The station also actually _plays_ the correct items.

![Screenshot 2023-10-12 at 15-04-44 ErsatzTV](https://github.com/ErsatzTV/ErsatzTV/assets/3706922/b10b07c6-5d32-4fb3-8c3b-d17400ee2573)

**Comment by jasongdove** [comment]
As stated in the screenshot "in priority order from top to bottom" meaning the top-most schedule overrides the default (bottom-most) schedule. Your override matches all days so the default will never be used, but that doesn't mean it's not a default.

**Comment by Moonbase59** [comment]
Hm, so I just misunderstand how it works and the _lowest_ is the "default", not the topmost? In any case odd from a usability perspective: You see (and click on) an alternate and what’s shown is something else…

Ok, thanks anyway, let’s close this if I just misunderstood.

**Comment by jasongdove** [comment]
Maybe easier to read in this format:

>    - Whenever a playout is built for a given day, ErsatzTV will check for a matching schedule from top to bottom 
>    - A given day must match all alternate schedule parameters; wildcards (`*any*`) will always match 
>      - Day of week 
>      - Day of month 
>      - Month 
>    - The lowest priority (bottom) item will always match all parameters, and can be considered a "default" or "fallback" schedule
