### ISSUE TITLE
HEVC gives 5xx error, H264 works fine

### ISSUE THREAD

**Issue by tedhinklater** [ErsatzTV/ErsatzTV#1498]
I encoded some h264 mkv's to hevc, the live tv channel returned:

06/11/2023 16:50:39 +00:00 | Information | ffmpeg hls  error arguments -nostdin -hide_banner -nostats -loglevel error -fflags  +genpts+discardcorrupt+igndts -loop 1 -copyts -i  C:\Users\thinklater\AppData\Local\ersatztv\cache\resources\background.png -f  lavfi -i anullsrc -filter_complex  [0:0]subtitles=C\\:/\Users/\thinklater/\AppData/\Local/\ersatztv/\temp-pool/\subtitle_4:fontsdir=C\\:/\Users/\thinklater/\AppData/\Local/\ersatztv/\cache/\streams/\fonts[v]  -map 1:0 -map [v] -muxdelay 0 -muxpreload 0 -movflags +faststart -flags  cgop -sc_threshold 0 -t 00:35:28.1940357 -r 24 -vsync cfr  -video_track_timescale 90000 -b:v 3000k -maxrate:v 3000k -bufsize:v  100000k -c:v libx265 -tag:v hvc1 -x265-params log-level=error -pix_fmt  yuv420p -c:a ac3 -ac 2 -b:a 192k -maxrate:a 192k -bufsize:a 384k -ar 48k  -map_metadata -1 -metadata "service_provider=\"ErsatzTV\"" -metadata  "service_name=\"kTV\"" -g 96 -keyint_min 96 -force_key_frames  expr:gte(t,n_forced*4) -f hls -hls_time 4 -hls_list_size 0  -segment_list_flags +live -hls_segment_filename  C:\Users\thinklater\AppData\Local\etv-transcode\4\live%06d.ts -hls_flags  program_date_time+append_list+discont_start+omit_endlist+independent_segments  -mpegts_flags +initial_discontinuity  C:\Users\thinklater\AppData\Local\etv-transcode\4\live.m3u8
-- | -- | --
06/11/2023 16:50:38 +00:00 | Error | HLS process  for channel 4 has terminated unsuccessfully with exit code -1482175992:  [in#0 @ 000001a5d5cdc480] Error opening input: Server returned 5XX  Server Error reply
06/11/2023 16:50:38 +00:00 | Information | Forcing 1 ffmpeg thread when hardware acceleration is used
06/11/2023 16:50:38 +00:00 | Information | ffmpeg hls  arguments -threads 1 -nostdin -hide_banner -nostats -loglevel error  -fflags +genpts+discardcorrupt+igndts -hwaccel dxva2 -ss  00:24:20.4360827 -c:v h264 -i  http://localhost:8409/media/jellyfin/3e0f39e31af6ec75895530aa48d5e3de -i   C:\Users\thinklater\AppData\Local\ersatztv\cache\artwork\logos\30\3009DDF99C6B7A2A4B00DB2B0E148674  -filter_complex  [0:1]loudnorm=I=-16:TP=-1.5:LRA=11,apad=whole_dur=1640436.0827ms[a];[0:0]scale=1920:1080:flags=fast_bilinear:force_original_aspect_ratio=decrease,setsar=1,pad=1920:1080:-1:-1:color=black[v];[1:0]format=yuva420p\|yuva444p\|yuva422p\|rgba\|abgr\|bgra\|gbrap\|ya8,scale=77:-1,colorchannelmixer=aa=0.30[wm];[v][wm]overlay=x=58:y=54:format=0[vwm];[vwm]setparams=range=tv:colorspace=bt709:color_trc=bt709:color_primaries=bt709[vpf]  -map [a] -map [vpf] -muxdelay 0 -muxpreload 0 -movflags +faststart  -flags cgop -sc_threshold 0 -t 00:03:00 -video_track_timescale 90000  -b:v 3000k -maxrate:v 3000k -bufsize:v 100000k -c:v hevc_amf -pix_fmt  yuv420p -c:a ac3 -b:a 192k -maxrate:a 192k -bufsize:a 384k -ar 48k  -map_metadata -1 -metadata "service_provider=\"ErsatzTV\"" -metadata  "service_name=\"kTV\"" -metadata:s:a:0 language=und -g 96 -keyint_min  96 -force_key_frames expr:gte(t,n_forced*4) -f hls -hls_time 4  -hls_list_size 0 -segment_list_flags +live -hls_segment_filename  C:\Users\thinklater\AppData\Local\etv-transcode\4\live%06d.ts -hls_flags  program_date_time+append_list+discont_start+omit_endlist+independent_segments  -mpegts_flags +initial_discontinuity  C:\Users\thinklater\AppData\Local\etv-transcode\4\live.m3u8
06/11/2023 16:50:38 +00:00 | Information | HLS segmenter will work ahead for channel 4
06/11/2023 16:50:38 +00:00 | Information | HLS session state: "SeekAndWorkAhead"
06/11/2023 16:50:38 +00:00 | Information | Starting HLS session for channel 4

I replaced the hevc batch with the h264 originals and it played correctly. This was the bat script i used with ffmpeg to encode:

for %%i in (*.mkv) do ffmpeg -i "%%i" -c:v hevc -preset slow -crf 23 -c:a copy -c:s copy "output\%%~ni.mkv"

Im playing back on the same desktop that is the server, should be direct playing like everything else but I just get that error message. Is it some encoding parameter I should change?

**Comment by tedhinklater** [comment]
ok I changed the filenames to "0001.mkv", "0002.mkv" etc and they play now. The original names were like "tiger_-_109826 (Original).mkv"

**Comment by jasongdove** [comment]
I would ensure you scan the libraries both in your media server and then in etv after replacing files. Etv caches things like codec, and it fails to decode hevc using h264 decoder.
