### ISSUE TITLE
Jellyfin cannot have hardware encoding enabled when using ErsatzTV hardware encoding.

### ISSUE THREAD

**Issue by JonathanC8** [ErsatzTV/ErsatzTV#1523]
So I found that when trying to have hardware transcoding encoding, I am not sure which I just know with those enabled it seems to break Jellyfin. I will have to either use encoding on ErsatzTV or Jellyfin. This is probable due to the fact that Jellyfin is attempting to hardware encode the stream after it has already been encoded by ErsatzTV. When you have both enabled you get Jellyfin saying the server is not providing a compatible media source. I also found that having the m3u file say it is using software encoding instead of hardware encoding solves the problem completely. Keep in mind I am using docker on linux mint for both, running these with an RTX 2060.

**Comment by JonathanC8** [comment]
Odd, it seems the issue has been fixed on my end after resetting the channels.m3u. Sometimes I have the change the bitrate and it seems to reset the stream so it's not a black screen.

**Comment by jasongdove** [comment]
> I also found that having the m3u file say it is using software encoding instead of hardware encoding solves the problem completely

Can you clarify what this means? I don't think the channel playlist gives any indication of whether hardware or software encoding is used - just the format. If you attempted different formats, perhaps Jellyfin had the old one cached?
