### ISSUE TITLE
Subtitle extraction question/improvement

### ISSUE THREAD

**Issue by boroborob** [ErsatzTV/ErsatzTV#1525]
Hi!

First of all, Merry Xmas! :)

I am using the docker version with Jellyfin, both running on top of Unraid.
Few weeks ago I've noticed that my disks are constantly being spun up at around the hour mark, at 8:00, 9:00, 10:00 and so on.
Have a lot of containers with all the *arrs, home automation and other stuff, so it took some time to track down the process spinning up my disks but finally found it in ErsatzTV's debug logs that it tries to extract the subtitles for the next playout items, even if nobody is watching any of the channels.
I have my media files spread across 8 disks and all of them are being spun up every hour, which might be a bit excessive
Previously had a problem with Jellyfin spinning up disks to read the poster files, images, etc, so I've moved every small file to my cache ssds and set it up so all files under 10MB would stay there, which solved the issue but since these subs are part of the media files i am not sure how to handle it.
First I thought, alright, I will just extract all the subs and that's it, but couldn't find an option to disable subtitle extraction, even if I would extract all the subs.
Also did some reading and tested subtitle extraction with ffmpeg -i $file -c copy -map 0:s:0 sub.srt together with the time command and quickly understood why the sub extraction isn't done on-the-fly right before playback: it took 88 seconds for a ~2 hour movie and that's just one sub stream... 

So, my question and request:
- is there an option to turn off subtitle extraction from media files and only use external ones? that way i could use a script the extract all my subtitles next to the media files, store them on the ssds and the disks wouldn't have to spin up.
- a setting field to set the frequency of sub extraction would be nice. For example daily or weekly,
 maybe even doing it in one go for the period specified in "Days to build" would be better than waking up the disks every hour, even if it takes hours for multiple day periods.
- or maybe an option to keep the extracted subs, so after a while it wouldn't have to do it?

Any ideas/solutions are much appreciated!
Happy Holidays!
Rob

**Comment by jasongdove** [comment]
Added two new subtitle-related settings to develop builds with #1590 

  - `Use embedded subtitles`
    - Default value: `true`
    - When disabled, embedded subtitles will not be considered for extraction (text subtitles), or playback (all embedded subtitles)

  - `Extract and use embedded (text) subtitles`
    - Default value: `false`
    - When enabled, embedded text subtitles will be periodically extracted, and considered for playback

**Comment by boroborob** [comment]
Thank, been testing it for a day, looks promising, hourly spikes are significantly reduced!

I don't fully understand the difference between the two settings though and didn't really had time to experiment with them yet, so just set them both to disabled.

What happens when 'Use embedded subtitles' is enabled but 'Extract and use' is disabled?
Are they extracted on the fly at playback instead of periodically?

**Comment by jasongdove** [comment]
Embedded image subtitles (PGS, dvdsub, etc) do not have to be extracted, so they can be overlayed at runtime without any pre-processing. This is what will be enabled by only the first option.

**Comment by jasongdove** [comment]
The first option was primarily added to allow users to disable/ignore all internal subtitles and only consider external subtitles. There isn't really a performance implication, which is why it defaults to true/enabled.

**Comment by boroborob** [comment]
Cool, I get it now, thank you!
