### ISSUE TITLE
Can´t playback many movies (smpte2084)

### ISSUE THREAD

**Issue by TahBui** [ErsatzTV/ErsatzTV#1526]
<img width="1478" alt="Screenshot_5" src="https://github.com/ErsatzTV/ErsatzTV/assets/138880136/7e6378ec-0a22-47ae-ba3c-e1483661ff88">
Started my ErsatzTV Journey today and it somewhat works, gpu is working and transcoding but it doesnt work on 2/3 of my movies. This error pops up everytime:
<img width="1374" alt="Screenshot_6" src="https://github.com/ErsatzTV/ErsatzTV/assets/138880136/8c259609-9a16-4929-afef-6d93a57641a4">
<img width="1435" alt="Screenshot_7" src="https://github.com/ErsatzTV/ErsatzTV/assets/138880136/362b3685-d47b-4a25-9149-0088a49d2ff6">

Can someone help me? Does anyone know more about this error?

sorry if somethings missing to debug or anything, am pretty new to this. If something else is needed, i will gladly post more.

**Comment by jasongdove** [comment]
HDR transcoding is not yet supported. See #1297

**Comment by jasongdove** [comment]
Closed as duplicate of #1297
