### ISSUE TITLE
Search for path/part of path

### ISSUE THREAD

**Issue by desertwitch** [ErsatzTV/ErsatzTV#1552]
It would be great if it would be possible to search media based on the path (e.g. a path: prefix) so that one could e.g. add all media where the path contains "myFolder" to a collection (path:myFolder)

**Comment by jasongdove** [comment]
Folders are added as tags for other video libraries. Will that work for you?

See https://ersatztv.org/docs/user-guide/local-libraries#other-video-fallback-metadata

**Comment by desertwitch** [comment]
Thanks, this is perfect.
