### ISSUE TITLE
Windows web ui went from perfect to massively large and unusable

### ISSUE THREAD

**Issue by attezz** [ErsatzTV/ErsatzTV#1577]
Happened overnight two nights ago.

The screen loads with the giant search icon showing first. 

All the channels and stuff are still running, but I'm unable to make any changes or updates through the webui

[Uploading ErsatzTV.pdf…]()

**Comment by attezz** [comment]
[ErsatzTV.pdf](https://github.com/ErsatzTV/ErsatzTV/files/14074561/ErsatzTV.pdf)
[ErsatzTV.pdf](https://github.com/ErsatzTV/ErsatzTV/files/14074562/ErsatzTV.pdf)

**Comment by jasongdove** [comment]
Do a hard reload: shift+refresh or ctrl+refresh, or try in a private window. Sometimes there are errors loading new versions of the web ui, but clearing the cache usually resolves it.
