### ISSUE TITLE
[Feature Request] Separate Admin WEB UI from channels.m3u/video flux

### ISSUE THREAD

**Issue by KawaKode** [ErsatzTV/ErsatzTV#1614]
Hello,

It would be very nice to be able to have the WEB UI as a whole separated from the video streaming part, that would allow anyone to host a website on the same domain used for the flux.

For example, let's say I'm WBCTV and my domain name is wbc.tv, it would be nice to have the flux be http://wbc.tv/flux.ts and have the website on the main domain and the admin UI would be on a subdomain or purely local to prevent intrusions.

Thanks !

**Comment by jasongdove** [comment]
There are a couple options currently available:

1. Only expose streaming endpoints by using a path prefix of `/iptv` - everything used for streaming is under that path prefix. The management UI does not use that path prefix for anything.

2. Use OIDC to protect the management UI

https://github.com/ErsatzTV/ErsatzTV/blob/c490832f66e1b22a2ff4a1293c60c659d35bab6a/CHANGELOG.md?plain=1#L423-L429
