### ISSUE TITLE
Heavy buffering and CPU usage even with QSV enabled

### ISSUE THREAD

**Issue by KawaKode** [ErsatzTV/ErsatzTV#1615]
Hello,

I use Ersatsz latest develop version (on Docker).

I enabled QSV but Ersatz seems to still only launch FFMpeg in software rendering mode.
HW accel should work, my CPU is an i5 1135G7, QSV/VAAPI works great in JellyFin and Plex (I also tried not running those but no dice)
![image](https://github.com/ErsatzTV/ErsatzTV/assets/75862028/b897ac7a-78bd-4511-84b3-abb1554e7f41)
Here are the logs from the troubleshooting page : 
[general.txt](https://github.com/ErsatzTV/ErsatzTV/files/14297567/general.txt)
[vaapi.txt](https://github.com/ErsatzTV/ErsatzTV/files/14297569/vaapi.txt)
[qsv.txt](https://github.com/ErsatzTV/ErsatzTV/files/14297570/qsv.txt)

Here the logs of when a stream is ongoing, nothing amiss : 

15/02/2024 14:06:57 +01:00 | Information | Terminating HLS session for channel 1
15/02/2024 14:06:57 +01:00 | Information | API termination request for HLS session for channel 1
15/02/2024 14:04:34 +01:00 | Information | Starting HLS session for channel 1
15/02/2024 14:04:34 +01:00 | Information | Starting ts stream for channel 1

The video would play for a bit, then buffer for a while and then play again. I tried both HLS Segmented and MPEG-TS. Here is my FFMPEG Config : 
![image](https://github.com/ErsatzTV/ErsatzTV/assets/75862028/bb07084b-9655-4db3-aad4-fe27e0cb04f7)

I tried changing the number of hardware frames, VAAPI/QSV, the buffer size, but no dice... I have a very stable gigabit fiber.
Note that client-side, the network activity looks like this, the pits correspond with when it starts buffering :  
![image](https://github.com/ErsatzTV/ErsatzTV/assets/75862028/8f252411-480b-4d64-a2fc-fadf5601e408)

Thanks for helping :)

**Comment by jasongdove** [comment]
The first thing that jumps out is your video buffer size. I wouldn't go any lower than 0.5x the bitrate, if you want to keep it low. ETV defaults to a buffer that is 2x the bitrate; yours is currently set to 0.1x the bitrate.

With that said, you will need to set the streaming log level to debug in ETV's main settings page and try streaming again to see log details about the transcoding process, including where hardware acceleration is/isn't used.

**Comment by KawaKode** [comment]
I enabled the debugging logs for streaming and adjusted the buffer to 10000kb for my 5000kb/s bitrate and launched the stream again : 

15/02/2024 15:39:26 +01:00 | Debug | WaitForPlaylistSegments took "00:00:05.1094448"
15/02/2024 15:39:26 +01:00 | Debug | Session started; returning multi-variant playlist for channel 1
15/02/2024 15:39:25 +01:00 | Debug | Segment count 0 of 1
15/02/2024 15:39:25 +01:00 | Debug | Playlist exists
15/02/2024 15:39:20 +01:00 | Debug | FFmpeg  pipeline  ["ThreadCountOption","NoStandardInputOption","HideBannerOption","NoStatsOption","LoglevelErrorOption","StandardFormatFlags","NoDemuxDecodeDelayOutputOption","FastStartOutputOption","ClosedGopOutputOption","NoSceneDetectOutputOption","TimeLimitOutputOption","VideoTrackTimescaleOutputOption","VideoBitrateOutputOption","VideoBufferSizeOutputOption","EncoderLibx264","EncoderAac","AudioChannelsOutputOption","AudioBitrateOutputOption","AudioBufferSizeOutputOption","AudioSampleRateOutputOption","DoNotMapMetadataOutputOption","MetadataServiceProviderOutputOption","MetadataServiceNameOutputOption","MetadataAudioLanguageOutputOption","OutputFormatHls","ComplexFilter"],  ["NormalizeLoudnessFilter","AudioPadFilter"], ["EncoderLibx264"]
15/02/2024 15:39:20 +01:00 | Debug | Playlist does not exist at expected location /root/.local/share/etv-transcode/1/live.m3u8
15/02/2024 15:39:20 +01:00 | Debug | ffmpeg hls  arguments -threads 0 -nostdin -hide_banner -nostats -loglevel error  -fflags +genpts+discardcorrupt+igndts -c:v hevc -readrate 1.0  -readrate_initial_burst 180 -stream_loop -1 -i  "/pool1/video/series/Psych/Season 3/Psych - S03E09 - Christmas Joy  WEBRip-1080p.mkv" -i  /root/.local/share/ersatztv/cache/artwork/watermarks/1E/1E2C94A4F1394035C3828C825C041A57  -filter_complex  [0:1]loudnorm=I=-16:TP=-1.5:LRA=11,apad=whole_dur=2582351.0528ms[a];[1:0]scale=288:-1[wm];[0:0][wm]overlay=x=W-w-96:y=54:format=0[vwm];[vwm]colorspace=irange=tv:ispace=bt709:itrc=bt709:iprimaries=bt709:all=bt709:format=yuv420p[vpf]  -map [a] -map [vpf] -muxdelay 0 -muxpreload 0 -movflags +faststart  -flags cgop -sc_threshold 0 -t 01:20:39.3228280 -video_track_timescale  90000 -b:v 5000k -maxrate:v 5000k -bufsize:v 10000k -c:v libx264 -c:a  aac -b:a 160k -maxrate:a 160k -bufsize:a 320k -ar 48k -map_metadata -1  -metadata "service_provider=\"ErsatzTV\"" -metadata  "service_name=\"LTV1\"" -metadata:s:a:0 language=fre -g 96 -keyint_min  96 -force_key_frames expr:gte(t,n_forced*4) -f hls -hls_time 4  -hls_list_size 0 -segment_list_flags +live -hls_segment_filename  /root/.local/share/etv-transcode/1/live%06d.ts -hls_flags  program_date_time+append_list+omit_endlist+independent_segments  /root/.local/share/etv-transcode/1/live.m3u8
15/02/2024 15:39:20 +01:00 | Debug | Waiting for playlist to exist
15/02/2024 15:39:20 +01:00 | Debug | FFmpeg  desired state FrameState { Realtime = False, InfiniteLoop = True,  VideoFormat = h264, VideoProfile = Some(main 10), PixelFormat =  Some(ErsatzTV.FFmpeg.Format.PixelFormatYuv420P), ScaledSize = FrameSize {  Width = 1920, Height = 1080 }, PaddedSize = FrameSize { Width = 1920,  Height = 1080 }, CroppedSize = None, IsAnamorphic = False, FrameRate =  None, VideoBitrate = Some(5000), VideoBufferSize = Some(10000),  VideoTrackTimeScale = Some(90000), Deinterlaced = False,  FrameDataLocation = Unknown, FFmpegAspectRatio = 16/9, BitDepth = 8 }
15/02/2024 15:39:20 +01:00 | Debug | Found  playout item Psych - Enquêteur malgré Lui - s03e09 - Noël au balcon,  tout le monde en prison with path /pool1/video/series/Psych/Season  3/Psych - S03E09 - Christmas Joy WEBRip-1080p.mkv
15/02/2024 15:39:20 +01:00 | Debug | HLS segmenter will work ahead for channel 1
15/02/2024 15:39:20 +01:00 | Debug | HLS session state: "SeekAndWorkAhead"
15/02/2024 15:39:20 +01:00 | Information | Starting HLS session for channel 1
15/02/2024 15:39:20 +01:00 | Debug | Preparing transcode folder /root/.local/share/etv-transcode/1
15/02/2024 15:39:20 +01:00 | Debug | Maybe starting ffmpeg session for channel 1
15/02/2024 15:39:03 +01:00 | Warning | Unable to locate session worker for channel 1
15/02/2024 15:39:01 +01:00 | Warning | Unable to locate session worker for channel 1
15/02/2024 15:39:00 +01:00 | Warning | Unable to locate session worker for channel 1
15/02/2024 15:38:58 +01:00 | Information | Terminating HLS session for channel 1
15/02/2024 15:38:58 +01:00 | Information | API termination request for HLS session for channel 1
15/02/2024 15:38:54 +01:00 | Debug | WaitForPlaylistSegments took "00:00:04.8452852"
15/02/2024 15:38:54 +01:00 | Debug | Session started; returning multi-variant playlist for channel 1
15/02/2024 15:38:54 +01:00 | Debug | Segment count 0 of 1
15/02/2024 15:38:54 +01:00 | Debug | Playlist exists

Thanks for your help !

**Comment by jasongdove** [comment]
Hmm. Something is not adding up. ETV caches hardware capabilities on startup, which includes some detail on detected entrypoints. I would stop the ETV container, start it back up and try streaming the channel one more time. Then, attach/link the contents of today's log file starting with `ErsatzTV version...`

**Comment by KawaKode** [comment]
Freshly extracted logs here : 
[ersatztv_logs(1).txt](https://github.com/ErsatzTV/ErsatzTV/files/14298380/ersatztv_logs.1.txt)

**Comment by jasongdove** [comment]
That's what I would expect to see when hardware acceleration is not enabled in the FFmpeg Profile; It does not include the expected log entries from detecting VAAPI/QSV capabilities.

**Comment by jasongdove** [comment]
Okay, I think the issue is that perhaps you have nothing scheduled except for fallback filler. Fallback filler will never use hardware acceleration due to bad behavior with infinite looping.

Is that what's happening here? The easiest schedule to test is a single schedule item set to dynamic start with playout mode flood. With that, the collection will play 24/7, but will also use hardware acceleration.

**Comment by KawaKode** [comment]
I have blocks that are programmed and the filler to fill in the gaps, I'll try changing that.

**Comment by jasongdove** [comment]
Okay, yeah, there isn't really great support for filler in blocks yet, unfortunately (other filler kinds do not loop and use hardware acceleration). That's under active development now. I believe if you test when an item is scheduled, you will see hardware acceleration working properly.

**Comment by KawaKode** [comment]
I just tried with just scheduling a collection and it uses VAAPI, no buffering :) 
Thanks for taking the time to help me with this 👍
