### ISSUE TITLE
[BUG] Music Video Artwork

### ISSUE THREAD

**Issue by SplitEnz** [ErsatzTV/ErsatzTV#1630]
I've noticed that the poster artwork for the music videos I have uploaded to my server are appearing fine on the server side, but the artwork link is not being passed to the EPG file. This results in no artwork appearing on the player side (Kodi).

**Comment by jasongdove** [comment]
Please paste your ErsatzTV version, found below the left menu.

**Comment by SplitEnz** [comment]
Sure, currently using:-
ErsatzTV Version
v0.8.5-beta-win-x64

**Comment by jasongdove** [comment]
This was fixed with https://github.com/ErsatzTV/ErsatzTV/pull/1598 and is currently available on develop builds. It will also be included in the next release.

I also just tested to reconfirm that the music video thumbnail makes it into the XMLTV as an icon entry, and it does.

**Comment by SplitEnz** [comment]
Great stuff.
Many thanks.
