### ISSUE TITLE
Library search function issue

### ISSUE THREAD

**Issue by Domjen2521** [ErsatzTV/ErsatzTV#1650]
Attempted to check some files today and when i went to the library option. When i choose the search magnifying glass on any folder from the library list, it will just show me everything instead of what is in the individual folder. this includes the jellyfin imported ones. I am currently using version 0.8.5-a45583d7

**Comment by jasongdove** [comment]
Thanks - this is a regression from https://github.com/ErsatzTV/ErsatzTV/pull/1648 which changed the default search analyzer (parsing logic) - will fix.

**Comment by jasongdove** [comment]
FYI the original search query (as entered in the UI) and the resulting query that is actually executed are now logged at debug level. If this happens with other searches, please include that information.
