### ISSUE TITLE
Music Video / Artist Images

### ISSUE THREAD

**Issue by tedhinklater** [ErsatzTV/ErsatzTV#1669]
I have a Music Videos folder. Inside, each Artist has a folder, with a few of their music videos inside. As a Music Video library/channel, it works, however in Jellyfin there is no image for each music video or artist, just the grey placeholder
 
![Screenshot 2024-04-06 140931](https://github.com/ErsatzTV/ErsatzTV/assets/66086488/617760db-83ab-4177-929c-a256aeea71be)

What does one need to do to display an artist image? Also, when I place an .nfo into the artist folder and scan the library, that artist is removed from the Music library until I delete the .nfo. Just to double-check, on the ErsatzTV dashboard, under Media, are Music Videos supposed to come under the heading "Music" (as they do for me) or "Music Videos" (which I haven't seen)?

![Screenshot 2024-04-06 141844](https://github.com/ErsatzTV/ErsatzTV/assets/66086488/fea7a748-3a6e-4236-aa4f-48ecb5b5d122)

**Comment by jasongdove** [comment]
Please include your ErsatzTV version, found below the left menu, when posting.

Music Videos support artist NFO metadata (name, genre, style, mood, biography), and artists will show up in the Music section.

Currently (v0.8.6-beta), the music video XMLTV template receives music video thumbnails, not artist thumbnails. If that is desired, we can make this a feature request.

**Comment by tedhinklater** [comment]
ErsatzTV Version
v0.8.6-beta-win-x64

Thanks for the speedy reply, the problem stands, if I place artist.nfo in the relevant artist's folder, the artist is removed from the Music section and there is a warning in the Logs. Is it a problem with the nfo? I've tried a few artists, this is the gorillaz' Artist.nfo

<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<artist>
  <biography>Gorillaz are an English virtual band created in 1998 by Damon Albarn and Jamie Hewlett. The band consists of four animated members: 2D (lead vocals, keyboard), Murdoc Niccals (bass guitar), Noodle (guitar, keyboard, and backing vocals) and Russel Hobbs (drums and percussion).</outline>
  <lockdata>false</lockdata>
  <dateadded>2022-09-17 22:09:30</dateadded>
  <title>Gorillaz</title>
  <runtime>0</runtime>
  <audiodbartistid>111393</audiodbartistid>
  <musicbrainzartistid>e21857d5-3256-4547-afb3-4b6ded592596</musicbrainzartistid>
  <art>
    <poster>Z:\Music\Gorillaz\Folder.jpg</poster>
    <fanart>C:\ProgramData\Jellyfin\Server\metadata\library\7b\7bab1c6f5757735ff03909176a04166b\backdrop.jpg</fanart>
  </art>
  <album>
    <title>Plastic Beach</title>
  </album>
</artist>

and this is the error

Error indexing artist with metadata {"Disambiguation":null,"Biography":"Gorillaz are an English virtual band created in 1998 by Damon Albarn and Jamie Hewlett. The band consists of four animated members: 2D (lead vocals, keyboard), Murdoc Niccals (bass guitar), Noodle (guitar, keyboard, and backing vocals) and Russel Hobbs (drums and percussion).","Formed":null,"ArtistId":4874,"Artist":null,"Styles":[],"Moods":[],"Id":134,"MetadataKind":"Sidecar","Title":null,"OriginalTitle":null,"SortTitle":null,"Year":null,"ReleaseDate":null,"DateAdded":"2024-04-06T14:58:08.5736954","DateUpdated":"2023-02-09T13:09:40.0658344","Artwork":null,"Genres":[],"Tags":null,"Studios":null,"Actors":null,"Guids":[],"Subtitles":null,"$type":"ArtistMetadata"}

**Comment by tedhinklater** [comment]
Thanks I'm gonna go buy some clown makeup

**Comment by jasongdove** [comment]
No worries, happy to help.
