### ISSUE TITLE
[Feature] Global filler and per-channel filler that works just like fallback filler but you don't call it that

### ISSUE THREAD

**Issue by wdstudios2** [ErsatzTV/ErsatzTV#1670]
Manually assigning hundreds of individual schedule items to use the exact same filler settings is a tedious, annoying pain in the ass. It would be better in every conceivable way to have the option to specify filler on a global or per-channel basis, with individual schedule item filler settings overriding channel settings and channel settings overriding global settings just like what is currently done with fallback filler. The easiest way to do this, by far, would be to just tweak the way fallback filler works by having it randomize at the end of each fallback filler item rather than at the end of each schedule item, and this would not, in any way, compromise the ability to use fallback filler settings for their originally intended purpose (if you want to loop a single filler item, you can just make a collection with a single filler item in it). However, if you prefer to implement this functionality in a needlessly difficult way, I won't complain. Someone might even find a use case for global pre-roll and post-roll filler settings.

**Comment by jasongdove** [comment]
This will not be added to the current filler system, but is planned for block scheduling and is under active development as a new "deco" system (to "decorate" channels with non-primary content) that defines watermarks, filler, etc that can be applied to playouts, and to specific times of day independent of the primary content (with `inherit`, `disable` and `override` modes to allow some of the flexibility you describe). Initial work supporting watermarks and fallback filler with the described modes is available on develop builds now.
