### ISSUE TITLE
Missing video on latest.vaapi

### ISSUE THREAD

**Issue by jsuzan** [ErsatzTV/ErsatzTV#1674]
upgraded instance to v0.8.6-beta and there is missing picture but audio.
 Used with enigma2 openATV 7.3 setup as iptv channels. On remote VLC or other player its ok
Video shows on previous image with no problem. 

the problem is in:
`
        if (desiredState.VideoFormat != VideoFormat.Copy)
        {
            pipelineSteps.Add(new NoBFramesOutputOption());
        }
`
and setting "-bf 0". This is somehow not working with GStreamer from enigma2 player

**Comment by jasongdove** [comment]
@jsuzan the latest develop build now has an option to allow b-frames in the ffmpeg profile editor. Please try and let me know if it fixes things for you.

**Comment by jsuzan** [comment]
it's working now, great afford :)
