### ISSUE TITLE
Unrecognized option 'readrate'.

### ISSUE THREAD

**Issue by curtwarfield** [ErsatzTV/ErsatzTV#1695]
Installed version:
ErsatzTV-v0.8.6-beta-linux-x64

OS:
Linux Mint 20.3

Unable to play:
Unrecognized option 'readrate'.
Error splitting the argument list: Option not found

**Comment by jasongdove** [comment]
See the health checks at the bottom of the home page (click on the ETV logo). Your ffmpeg version is probably lower than 6.1.

You can download this version, extract it somewhere, then point ETV to it in ETV's main settings page.

https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n6.1-latest-linux64-gpl-6.1.tar.xz
