### ISSUE TITLE
Edit Schedule, Start Type Only dynamic, Start time greyed out. How do I make a proper tv guide channel lineup?

### ISSUE THREAD

**Issue by superdong69** [ErsatzTV/ErsatzTV#1716]
I want to add shows to a channel, and have them start at a certain time. Starting at 6:00am, until midnight. I have show to fill the entire day, and I want each to air at a certain time. But under each channel, the only option I have is Dynamic, and the start time is greyed out.

**Comment by jasongdove** [comment]
See `Shuffle Schedule Items` at https://ersatztv.org/docs/user-guide/create-channels#create-schedule

> This shuffles the order of schedule items when building a playout, and is mostly used on channels with a mix of shows that require unique schedule item settings per show. Note that this disables fixed start times and flood mode.

**Comment by superdong69** [comment]
" while a Fixed start type requires a start time."

I only have Dynamic in the drop down, there is no "fixed" option. Or am I blind?

**Comment by jasongdove** [comment]
Go to the page where you can edit the schedule's name and see if you have `Shuffle Schedule Items` enabled. If so, the quoted details apply, specifically

> Note that this **disables fixed start times** and flood mode.

**Comment by superdong69** [comment]
That was it! Thank you!
