### ISSUE TITLE
Subtitles option defined in Schedules, but the subtitltes don't appears

### ISSUE THREAD

**Issue by paivadaniel** [ErsatzTV/ErsatzTV#1721]
Hello, after reading this thread: https://github.com/ErsatzTV/ErsatzTV/issues/45

I tested the ErsatzTV versions: 

ErsatzTV-v0.8.6-2c97c497-linux-x64
ErsatzTV-v0.8.6-beta-linux-x64

For both, when filling the items in the Schedule tab, I tested all possible subtitle options:

![Screenshot from 2024-05-20 17-40-21](https://github.com/ErsatzTV/ErsatzTV/assets/95258585/7a3b5f59-c22e-4208-a567-510191135b5b)

However, in VLC, MPV, and TiviMate, the available subtitle options did not appear. And the libraries were scanned again. Is there any other place that I should set the subtitle options so that they are displayed?

**Comment by jasongdove** [comment]
To clarify - ETV burns subtitles that it finds into the video stream; it does not deliver them separately. Also, embedded text subtitles are disabled by default because they need to be extracted in advance which adds overhead. If those are the subtitles you want, you can turn them on in ETV's main settings page.

**Comment by c0pper** [comment]
> To clarify - ETV burns subtitles that it finds into the video stream; it does not deliver them separately. Also, embedded text subtitles are disabled by default because they need to be extracted in advance which adds overhead. If those are the subtitles you want, you can turn them on in ETV's main settings page.

Hi jason, I'm facing the same difficulty in displaying subtitles. Is this the main settings page you're referring to? I don't see any setting for subtitles in here... Can you please advise? Thanks

![image](https://github.com/ErsatzTV/ErsatzTV/assets/18085925/d4963b48-b916-4bfc-818c-46c8cbe2b72c)
