### ISSUE TITLE
ffmpeg 7 causes many play problems. Switching back to 6.1 sort them

### ISSUE THREAD

**Issue by jsuzan** [ErsatzTV/ErsatzTV#1728]
ffmpeg 7 causes many play problems. Switching back to 6.1 sort them

_Originally posted by @jsuzan in https://github.com/ErsatzTV/ErsatzTV/issues/1723#issuecomment-2131313948_

... even Preview Channel does not play most media

**Comment by jasongdove** [comment]
Yes, ffmpeg 7.0 introduced many regressions for Intel devices (VAAPI and QSV). I've been trying to fix today; will need to build a snapshot of a newer ffmpeg.

**Comment by jsuzan** [comment]
if you need some logs, I would get them...

**Comment by jasongdove** [comment]
I don't need to logs, thanks; as I said I have already been working on this issue. I have a repro case, and I know what changes in ffmpeg caused the regression. I just need to get an updated ffmpeg snapshot working in docker at https://github.com/ErsatzTV/ErsatzTV-ffmpeg

**Comment by jasongdove** [comment]
This should be fixed with https://github.com/ErsatzTV/ErsatzTV-ffmpeg/pull/16 and https://github.com/ErsatzTV/ErsatzTV/pull/1729 - please pull and test.

**Comment by jsuzan** [comment]
FIX it is :) tested seems OK
