### ISSUE TITLE
[Feature Request] Raspberry Pi hardware acceleration

### ISSUE THREAD

**Issue by peterdey** [ErsatzTV/ErsatzTV#1731]
I've got hardware transcoding on a Raspberry Pi CM4 working using ffmpeg from https://github.com/jc-kynesim/rpi-ffmpeg (tested as working with tag [pi/5.1.4/rpi_23](https://github.com/jc-kynesim/rpi-ffmpeg/tree/pi/5.1.4/rpi_23) and branch [test/6.0.1/main](https://github.com/jc-kynesim/rpi-ffmpeg/tree/test/6.0.1/main)).  I know the minimum recommended version is 6.1, particularly to get readrate_initial_burst.

My current super-hacky workaround is placing the ffmpeg binary produced from one of the branches/tags above in /usr/local/bin as `ffmpeg2`, and a bash script called `ffmpeg` that injects the needed parameters to get hardware acceleration working.

I have tried using the videotoolbox accelerator in the ErsatzTV codebase as a template, but with the pipeline construction and other bits, it was a bit beyond me 🙂

There's only two changes needed to the target ffmpeg commandline:
- Add `-hwaccel drm` (I think this is to enable the hardware decoding)
- Assuming h264 encoding, change `-c:v libx264` to `-c:v h264_v4l2m2m` for the encoder.

All the other arguments produced by the software encoder worked fine.  More performance gains might be possible using hardware accelerated filters, but I have not tested this (and even seems like this [might be impossible](https://github.com/jc-kynesim/rpi-ffmpeg/issues/42#issuecomment-1465142500) due to differing pixel formats).

Detection:
```
$ ./ffmpeg -hwaccels 2>/dev/null
Hardware acceleration methods:
drm
```

Codecs:
```
$ ./ffmpeg -encoders 2>/dev/null |grep v4l2m2m 
 V..... h263_v4l2m2m         V4L2 mem2mem H.263 encoder wrapper (codec h263)
 V..... h264_v4l2m2m         V4L2 mem2mem H.264 encoder wrapper (codec h264)
 V..... hevc_v4l2m2m         V4L2 mem2mem HEVC encoder wrapper (codec hevc)
 V..... mpeg4_v4l2m2m        V4L2 mem2mem MPEG4 encoder wrapper (codec mpeg4)
 V..... vp8_v4l2m2m          V4L2 mem2mem VP8 encoder wrapper (codec vp8)
```

Let me know if you need any more details.  I can test any builds or patches.

**Comment by jasongdove** [comment]
Thanks for the info - I don't have the appropriate hardware right now to test and add it, but I'll see what I can find.

**Comment by K-VIJAYARAJAN** [comment]
Can you give more details on the super hack to enable hardware acceleration using bash script,
Kindly attach working example of the bash script

**Comment by K-VIJAYARAJAN** [comment]
> I've got hardware transcoding on a Raspberry Pi CM4 working using ffmpeg from https://github.com/jc-kynesim/rpi-ffmpeg (tested as working with tag [pi/5.1.4/rpi_23](https://github.com/jc-kynesim/rpi-ffmpeg/tree/pi/5.1.4/rpi_23) and branch [test/6.0.1/main](https://github.com/jc-kynesim/rpi-ffmpeg/tree/test/6.0.1/main)). I know the minimum recommended version is 6.1, particularly to get readrate_initial_burst.
> 
> My current super-hacky workaround is placing the ffmpeg binary produced from one of the branches/tags above in /usr/local/bin as `ffmpeg2`, and a bash script called `ffmpeg` that injects the needed parameters to get hardware acceleration working.
> 
> I have tried using the videotoolbox accelerator in the ErsatzTV codebase as a template, but with the pipeline construction and other bits, it was a bit beyond me 🙂
> 
> There's only two changes needed to the target ffmpeg commandline:
> 
> * Add `-hwaccel drm` (I think this is to enable the hardware decoding)
> * Assuming h264 encoding, change `-c:v libx264` to `-c:v h264_v4l2m2m` for the encoder.
> 
> All the other arguments produced by the software encoder worked fine. More performance gains might be possible using hardware accelerated filters, but I have not tested this (and even seems like this [might be impossible](https://github.com/jc-kynesim/rpi-ffmpeg/issues/42#issuecomment-1465142500) due to differing pixel formats).
> 
> Detection:
> 
> ```
> $ ./ffmpeg -hwaccels 2>/dev/null
> Hardware acceleration methods:
> drm
> ```
> 
> Codecs:
> 
> ```
> $ ./ffmpeg -encoders 2>/dev/null |grep v4l2m2m 
>  V..... h263_v4l2m2m         V4L2 mem2mem H.263 encoder wrapper (codec h263)
>  V..... h264_v4l2m2m         V4L2 mem2mem H.264 encoder wrapper (codec h264)
>  V..... hevc_v4l2m2m         V4L2 mem2mem HEVC encoder wrapper (codec hevc)
>  V..... mpeg4_v4l2m2m        V4L2 mem2mem MPEG4 encoder wrapper (codec mpeg4)
>  V..... vp8_v4l2m2m          V4L2 mem2mem VP8 encoder wrapper (codec vp8)
> ```
> 
> Let me know if you need any more details. I can test any builds or patches.

Please post more details on the bash script used

**Comment by peterdey** [comment]
Sorry @K-VIJAYARAJAN - after messing around for months trying to get stable streams on a Raspberry Pi, I gave up.  The hardware just simply is not capable.  Switching channels would often cause a kernel panic.

I moved to a RK3588 instead - no regrets.
