### ISSUE TITLE
Possible FFMPEG Issue

### ISSUE THREAD

**Issue by Domjen2521** [ErsatzTV/ErsatzTV#1735]
I started to have issues with the ErsatTV program when the version 7 file was being used. The loading time for the stream takes a lot longer than normal. This didnt start to happen until the activation of version 7. i was able to narrow down the issue by rolling back the ffmpeg.exe file back to the one from 03-26-2024 64bit. when i use this version the streams load up faster. i am using mkv files mostly. and using hls segmenter. i have not attempted using v2 just yet. any ideas to try out are greatly appreciated. my pc is windows 11 intel I5-6600 @ 3.30 3.31 with 16gb ram and nivida geforce gtx 1660 super.

**Comment by jasongdove** [comment]
Can you paste the ffmpeg arguments from the log file? You may need to set streaming log level to `Debug` in ETV's main settings page first. With that info, I'll try to reproduce here.

**Comment by Domjen2521** [comment]
![ScreenHunter_412 May  30 11 05](https://github.com/ErsatzTV/ErsatzTV/assets/86805738/b165612f-0795-4707-9863-1fc39464e47b)
![ScreenHunter_413 May  30 11 06](https://github.com/ErsatzTV/ErsatzTV/assets/86805738/88777e14-4cc4-49c3-ac9c-873d3a809e9d)

**Comment by jasongdove** [comment]
What do you see in the Troubleshooting page > NVIDIA section?

**Comment by Domjen2521** [comment]
I upgraded the nvidia drivers thinking that might be an issue and i get this in the troubleshooting for nvidia.

ffmpeg version n7.0-88-g85d4df3873-20240524 Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 13.2.0 (crosstool-NG 1.26.0.65_ecc5e41)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-nonfree --enable-gpl --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-fontconfig --enable-libharfbuzz --enable-libvorbis --enable-opencl --disable-libpulse --enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-chromaprint --enable-libdav1d --enable-libdavs2 --enable-libdvdread --enable-libdvdnav --enable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-nvenc --enable-nvdec --enable-frei0r --enable-libgme --enable-libkvazaar --enable-libaribcaption --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libssh --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --enable-libvpl --enable-openal --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --enable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-d3d11va --enable-dxva2 --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-libs=-lgomp --extra-ldflags=-pthread --extra-ldexeflags= --cc=x86_64-w64-mingw32-gcc --cxx=x86_64-w64-mingw32-g++ --ar=x86_64-w64-mingw32-gcc-ar --ranlib=x86_64-w64-mingw32-gcc-ranlib --nm=x86_64-w64-mingw32-gcc-nm --extra-version=20240524
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
Input #0, lavfi, from 'nullsrc':
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: wrapped_avframe, yuv420p, 320x240 [SAR 1:1 DAR 4:3], 25 fps, 25 tbr, 25 tbn
Stream mapping:
  Stream #0:0 -> #0:0 (wrapped_avframe (native) -> h264 (h264_nvenc))
Press [q] to stop, [?] for help
[h264_nvenc @ 000001bb5653ae40] [ GPU #0 - < NVIDIA GeForce GTX 1660 SUPER > has Compute SM 7.5 ]
[vost#0:0/h264_nvenc @ 000001bb5653aa80] Error while opening encoder - maybe incorrect parameters such as bit_rate, rate, width or height.
[vf#0:0 @ 000001bb56555e80] Error sending frames to consumers: Immediate exit requested
[vf#0:0 @ 000001bb56555e80] Task finished with error code: -1414092869 (Immediate exit requested)
[vf#0:0 @ 000001bb56555e80] Terminating thread with return code -1414092869 (Immediate exit requested)
[vost#0:0/h264_nvenc @ 000001bb5653aa80] Could not open encoder before EOF
[vost#0:0/h264_nvenc @ 000001bb5653aa80] Task finished with error code: -22 (Invalid argument)
[vost#0:0/h264_nvenc @ 000001bb5653aa80] Terminating thread with return code -22 (Invalid argument)
[out#0/null @ 000001bb564e9a00] Nothing was written into output file, because at least one of its streams received no packets.
frame=    0 fps=0.0 q=0.0 Lsize=       0KiB time=N/A bitrate=N/A speed=N/A

**Comment by jasongdove** [comment]
The driver was the issue, this is a successful result.

 > [h264_nvenc @ 000001bb5653ae40] [ GPU #0 - < NVIDIA GeForce GTX 1660 SUPER > has Compute SM 7.5 ]

Does it behave as normal now? Maybe after restarting ETV?

**Comment by Domjen2521** [comment]
thank you for all the help, it definitely works a lot better now. it loaded up very efficiently.
