### ISSUE TITLE
[Feature Request] Exclude episodes from schedule items

### ISSUE THREAD

**Issue by daftblazer** [ErsatzTV/ErsatzTV#1748]
Would be nice to add the ability to exclude episodes from a schedule item based on certain criteria. For example, Episodes or seasons that do not contain english audio. I am not sure if .ass subtitles work or not, but I could not get them to, nor do I really want to burn subtitles. However, I have some shows where some episodes are not yet dubbed in english. 

I could just manually go through every season to see what is dubbed and only add those certain seasons. But it would be nice if when those episodes meet the criteria (english audio) they automatically become available in the schedule.

**Comment by jasongdove** [comment]
If you use smart collections you can use `language` or `language_tag` to automatically filter. See https://ersatztv.org/docs/user-guide/search
