### ISSUE TITLE
Plex Media Source getting wrong IP Address

### ISSUE THREAD

**Issue by zdhoward** [ErsatzTV/ErsatzTV#1751]
I have PLEX running in a container on my UNRAID server and I have ErsatzTV running on my windows machine.
This setup has been working really well for me for the past couple of months but recently I moved and am unable to remotely use my Plex server anymore.
This isn't a problem as I usually just watch on my home network but now that I am using direct local connections to Plex, ErsatzTV has started using the container IP address on my UNRAID machine (which is not exposed to the network as I port forward the container port to the server IP).

Would love it if there was a way I could manually set up the IP address for my plex server to point to the UNRAID server with port forwarding.

**Comment by jasongdove** [comment]
ETV will test all advertised Plex addresses on startup, and shouldn't use an address where Plex can't be reached. You can either add more addresses in Plex's settings, or you can ensure that DNS rebinding works for plex.direct so they resolve internally. Plex exposes all potential internal IPs that way.
