### ISSUE TITLE
Most posters are not showing

### ISSUE THREAD

**Issue by ItsNoted** [ErsatzTV/ErsatzTV#1757]
I'm curious why only a few posters are showing under my shows media library. Most of them are missing. Is there a setting I need to enable or is this a bug? I'm using the Docker image.

**Comment by jasongdove** [comment]
Please provide some more details:

1. ETV version found below the left menu
2. Media Source (local, Plex, Jellyfin, Emby)

Also, do you see any errors in the browser's network monitor for the images?

**Comment by ItsNoted** [comment]
I’ve tried both windows and docker versions. But 0.8.6-beta-win-x64 currently testing on windows is also only adding some posters.

I’m using local sources it finds and adds the media fine and lets me use it without issue. It just seems to avoid adding data for most series while very few it has.

**Comment by jasongdove** [comment]
Can you give examples of the folder layout and filenames? My initial guess is that your posters are named differently in different folders. ETV supports `poster` and `folder` with one of the extensions `jpg`, `jpeg`, `png`, `gif`, `tbn`, `webp`; e.g. `poster.jpg` or `folder.png`. This file needs to be in the show root folder.

https://github.com/ErsatzTV/ErsatzTV/blob/f7f1a0493b9801dab8648a6a8bf14569b304ea1b/ErsatzTV.Scanner/Core/Metadata/TelevisionFolderScanner.cs#L597-L613

**Comment by ItsNoted** [comment]
Ok, So I figured out how to do this.

1. Enable metadat from NFO in Emby
2. Enable NFO downloader in Emby
3. Downloadartwork to folders checked in Emby

All good now :)

**Comment by jasongdove** [comment]
Awesome, glad you figured it out.

Yeah, ETV does not provide/generate any metadata, it just uses what it can find.
