### ISSUE TITLE
Unable to remove deleted items from Ersatz library

### ISSUE THREAD

**Issue by c0pper** [ErsatzTV/ErsatzTV#1768]
So I added a local library that points to a folder of MTV Bumpers videos and then I realized some of those are too recent for what I'm going for, so i deleted them and rescanned the library by clicking on the refresh icon. However the deleted files still show up as missing in the UI (see pic). Is there any way of removing these now deleted files to avoid the channel showing missing files message? Or do i have to delete and recreate the library (which would be annoying because I also have to recreate the mtv bumpers collection and readd the collection wherever is supposed to play in my schedule)?

![image](https://github.com/ErsatzTV/ErsatzTV/assets/18085925/447d218f-4dd3-4773-9380-d5dd3e6d6b80)

**Comment by WallaWallaWA** [comment]
From the main menu (on the left of the screen), select Media, then select [Trash](https://imgur.com/wIP7TPD). It will then display those deleted items and you can empty the trash.

**Comment by c0pper** [comment]
Thanks, learned something new :)
