### ISSUE TITLE
Limit access to channels per user?

### ISSUE THREAD

**Issue by Sevyn13** [ErsatzTV/ErsatzTV#1775]
Is it possible to limit certain channels so they are not accessible by my children? I'd Like to have some Kid's channels and that the only channels they have access to. My children each have their own Plex account.

**Comment by jasongdove** [comment]
ETV doesn't allow multiple versions (subsets) of the channel list.

Maybe see if something like https://github.com/Threadfin/Threadfin can be used as an intermediary for that purpose.
