### ISSUE TITLE
Accessing M3U channel list from OpenATV set top box

### ISSUE THREAD

**Issue by Sitehand** [ErsatzTV/ErsatzTV#1777]
I have just started using ErsatzTV and I am connecting to it from an OpenATV Enigma2 set top box. If I download the channels.m3u from the ErsatzTV interface and upload it to the set top box the channels are processed correctly. However if I give the URL to the plugin to access it directly, it fails and returns a message that it cannot access the site.

I turned on debug in ErsatzTV and found the following message when it tries to access the m3u link.
HTTP HEAD /iptv/channels.m3u responded 405 in 0.1361 ms

Is there anything I can do to allow the set top box to access the file directly.

Thanks
Daniel

**Comment by jasongdove** [comment]
@Sitehand please test the latest develop build with the fix by @raknam

https://github.com/ErsatzTV/ErsatzTV/releases/tag/develop

**Comment by Sitehand** [comment]
@jasongdove I have confirmed that the latest develop build does fix the issue.

**Comment by jasongdove** [comment]
Fixed by #1779
