### ISSUE TITLE
After pausing HLS Segmenter livestream on jellyfin, it can deadlock

### ISSUE THREAD

**Issue by ShadowJonathan** [ErsatzTV/ErsatzTV#1789]
I'm using HLS Segmenter directly instead of MPEG-TS, since that one fills up my diskspace when I accidentally pause the livestream for too long, and takes a while longer to load on Jellyfin.

However, pausing HLS Segmenter seems to eventually time out the stream, and make the worker stop. On Jellyfin's side, this then makes the player become the watermark image, but after pressing "play", it does not restart.

Usually I'd expect jellyfin to then snap to the latest time on the livestream, but here that doesn't seem to happen, and instead ETV is just stopping the worker, while not seeing to restart it after pressing "play" in Jellyfin.

**Comment by jasongdove** [comment]
The URL in the channels.m3u returns a multi-variant playlist AND starts the transcoding session for the channel. Inside that playlist is one variant playlist URL that can be used for playback. This variant playlist URL will fail if no transcoding session is active.

I'll give this some thought. I'm not sure if there would be a downside to having the variant playlist also (re-)start a transcoding session.

**Comment by ShadowJonathan** [comment]
This has indeed fixed the problem, but it seems to crash Jellyfin now.

This isn't a problem for ersatztv to fix, but still notable.

Thanks for merging!
