### ISSUE TITLE
[Bug] Prefered subtitle language do not work for Brazilian Portuguese

### ISSUE THREAD

**Issue by felipemarinho97** [ErsatzTV/ErsatzTV#1801]
![image](https://github.com/user-attachments/assets/a14dcd62-c36d-4c14-ad8c-936fd2c9c9e4)

All of my content has `pob` (Brazilian Portuguese) subtitles but they are not working with the config "Prefered subtitle language".
This config is only working for content with Portugues from portugal (`pop`/`por`).

**Comment by felipemarinho97** [comment]
Maybe this is also the issue here too #1721 ?

**Comment by jasongdove** [comment]
Please try with the latest develop build, there have been a couple subtitle fixes after the 0.8.7 release

https://github.com/ErsatzTV/ErsatzTV/pull/1798 and https://github.com/ErsatzTV/ErsatzTV/pull/1814

**Comment by jasongdove** [comment]
Nevermind, it looks like `pob` is not present in the database or in .NET's CultureInfo. It looks like it's not an official language code, so I'll have to give this one some more thought.

**Comment by jasongdove** [comment]
@felipemarinho97 please try with the latest develop build now after https://github.com/ErsatzTV/ErsatzTV/pull/1822

`pob` should be present at the bottom of the list.

**Comment by felipemarinho97** [comment]
@jasongdove Hey! thanks for taking a look at this

I can select `pob` from the list, but cannot create the channel:
```
[23:47:55 ERR] Unexpected error saving channel: Preferred subtitle language code is invalid
```

When editing a existing channel the "Save" button worked but I can`t see any subs rendered:
```
[23:45:54 DBG] Found no subtitles for channel 1 with mode Any matching language []
```

**Comment by jasongdove** [comment]
@felipemarinho97 I made a test `pob` srt file and fixed a couple more issues with https://github.com/ErsatzTV/ErsatzTV/pull/1823

Please test again.

**Comment by felipemarinho97** [comment]
@jasongdove Hey thank you! now it's working! 🎉 

I dont know why "Brazilian Portuguese" is not in .NET's CultureInfo. But it is not just any random dialect or creole, there are more than 200 million speakers. Maybe this can be added to the list with the correct english name as an improvement in the future. The values should be:

3-code: pob
2-code: pt-BR

For now, as this has already solved my problem so I'm happy 😄

**Comment by jasongdove** [comment]
To be clear, `pt-BR` is present in CultureInfo and has the English name `Portuguese (Brazil)` - my understanding is that the unofficial/unsupported part is specifically the code `pob`.
