### ISSUE TITLE
Does not scan local files (movie or shows)

### ISSUE THREAD

**Issue by SergioDG-YCC** [ErsatzTV/ErsatzTV#1805]
Hello. Thank you very much for your software. I'm running into a problem using version 0.8.7-beta-docker on docker 25.0.0, Ubuntu 22.04.3 LTS

I have not been able to read movie or show folders locally. It works with Jellyfin, but that's not the idea. Other videos work fine. The folders and their content are seen correctly in the console (docker exec -it ersatztv bash)

I have added .nfo and .jpg generated by Kodi, Jellyfin and my own. Does not show items

Could it be a problem with Docker?
All my implementation is 'root'

**Comment by madorian** [comment]
It works for me, just tried this app out today. 

How do you add your libraries inside the gui?

**Comment by SergioDG-YCC** [comment]
I have added a LOCAL library of movies and another of series. It scans but does not list any files. Each movie has its corresponding NFO and Poster. If I add through the Jellyfin API it works, but it is not how my instance should work.

**Comment by jasongdove** [comment]
Closing this as it was solved here https://discuss.ersatztv.org/d/113-does-not-scan-local-files-movie-or-shows

For reference, local libraries have folder layout requirements which are described here https://ersatztv.org/docs/user-guide/local-libraries#folder-layout
