### ISSUE TITLE
Failed Scanning of Media Libraries

### ISSUE THREAD

**Issue by Domjen2521** [ErsatzTV/ErsatzTV#1828]
Having an issue with the most recent update. it seems that the scanning of the library to update for new files added does not work.

i am currently using version v0.8.7-ec99d597-win-x64. also the previous version is doing the same when i roll back. the logs state that the tv scanner file is missing. i tend to just replace the most recent download with the files and make a backup of the previous. it shows the ersatztvscanner file is not present on the last two releases.

<html><body>

7/28/2024 2:39:34 PM -05:00 | Debug | Search query parsed from [type:show AND (library_id:24)] to [+type:show +library_id:24]
-- | -- | --
7/28/2024 2:39:34 PM -05:00 | Debug | Search query parsed from [type:movie AND (library_id:24)] to [+type:movie +library_id:24]
7/28/2024 2:39:32 PM -05:00 | Warning | Unable to synchronize jellyfin library 24: Unable to locate ErsatzTV.Scanner executable
7/28/2024 2:39:32 PM -05:00 | Information | Successfully synchronized Jellyfin libraries for source 2

</body>
</html>

**Comment by jasongdove** [comment]
Thanks for the report, this is fixed in the latest develop build

```shell
% 7z l ErsatzTV-v0.8.7-728c5130-win-x64.zip | grep exe
2024-07-28 17:40:41 ....A       417280       174554  ErsatzTV-Windows.exe
2024-07-28 17:39:18 ....A     75575410     69062541  ErsatzTV.exe
2024-07-28 17:38:39 ....A     64436897     58032731  ErsatzTV.Scanner.exe
2023-11-21 13:17:52 ....A    119685120     43427623  ffmpeg.exe
2023-11-21 13:17:52 ....A    119556096     43365043  ffprobe.exe
```
