### ISSUE TITLE
Adding Trakt list resulted in Response status code does not indicate success: 412 (Precondition Failed).

### ISSUE THREAD

**Issue by dsync89** [ErsatzTV/ErsatzTV#1855]
Somehow I only got this error when adding my own Trakt list. Those list were public so it shouldn't be permission issue.

Example trakt list that failed:
https://trakt.tv/users/d-sync/lists/alien

Others trakt list imported just fine
https://trakt.tv/users/hdlists/lists/best-of-the-2010s?sort=rank,asc

![image](https://github.com/user-attachments/assets/8544057e-252e-406f-a10f-7594708d0912)

**Comment by jasongdove** [comment]
The issue is the special character `.` in the user name. Will work on a fix.
