### ISSUE TITLE
Constant spinning circle on Playout Page, channel by channel

### ISSUE THREAD

**Issue by dsync89** [ErsatzTV/ErsatzTV#1858]
I've noticed that there will be a spinning circle whenever I check the Playout page, which suggest that ErsatzTV is constantly regenerating the playout channel by channel. It does goes from the top channel to the bottom, and then probably repeat itself. This causes problem if I change the content in the schedule (say adding fillters). I have to wait for the existing Playout queue to clear before the playout for the new schedule is refreshed. I've sometimes seen the spinning circle on all the Playout channels.

If I understand the logic correctly, the playout should only be run after it detect there is a library change, which I set to 1 day, but I'm seeing the Playout spinning icon every time I visit that page within the one day period.

![image](https://github.com/user-attachments/assets/333f2982-1551-453e-84f5-20b28c40d1d1)

Just out of curiosity, how does Ersatv decide when to refresh the playout? Say I have both Playout and Program Guide to build for 2 days, will the new playout and EPG refreshed few hours before the 2 days period? Would be best if we have a way to set when the playout get refreshed, either

**Comment by jasongdove** [comment]
What version of ETV are you running? Please paste the version number found below the left menu.

Is it the same playout every time you check the page, or is it different playouts? Do you see any warnings or errors in the logs?

**Comment by dsync89** [comment]
@jasongdove I'm using version `0.8.7-55b7a356-docker-vaapi`. THespinning circle will happen on different playout each time I checked, and is always the subsequent ones from the last one it processed. I believe once it processed the last playout, it will restart again from the first playout and continue.

After enabling debug logs I think I might know what caused it. 

This only occurs after I enabled `Extract and use embedded (text) subtitles` option in the settings, as the log show `Extracting embedded subtitle for ...`. Ever since I disabled it and restart, I no longer see the spinning circle for the playout.

**Comment by jasongdove** [comment]
Ah okay, that can be a *very* slow process depending on the specifics of your system. Subtitle extraction happens every hour, and if you have enough channels with subtitles enabled, I could see it taking the entire hour and essentially running forever. This is why the setting is disabled by default; external subtitles give a much better experience.
