### ISSUE TITLE
Can't install the Docker (unRaid)

### ISSUE THREAD

**Issue by DCPDad** [ErsatzTV/ErsatzTV#1884]
Hello!

I am excited to test out this cool application - thank you for creating it.

When I try to install the Docker on my unRaid system (v 6.12.13), I get the following:
docker run
  -d
  --name='ErsatzTV'
  --net='host'
  --pids-limit 2048
  -e TZ="America/Los_Angeles"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="RackServer"
  -e HOST_CONTAINERNAME="ErsatzTV"
  -e 'TCP_PORT_8409'='8409'
  -e 'NVIDIA_VISIBLE_DEVICES'='GPU-xxxxxxx' (<----, of course, I use the complete ID here)
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:8409]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/RandomNinjaAtk/unraid-templates/master/randomninjaatk/img/ersatztv.png'
  -v '/mnt/user/appdata/ErsatzTV':'/root/.local/share/ersatztv':'rw' add
  --runtime=nvidia 'jasongdove/ersatztv:develop-nvidia'
Unable to find image 'add:latest' locally
docker: Error response from daemon: pull access denied for add, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

I have tried both the 'latest' and the 'develop' for -nvidia and get the same results for both.

Any thoughts?

**Comment by DCPDad** [comment]
My bad!
I eliminated the "add ", and it installed fine.

**Comment by embolon** [comment]
Should close as it already resolved.
