### ISSUE TITLE
[FEATURE_REQUEST] Add Authentication and 2FA Support

### ISSUE THREAD

**Issue by deffcolony** [ErsatzTV/ErsatzTV#1913]
I would like to request the addition of authentication features (username and password) for accessing the ErsatzTV web interface. This is especially important when the app is exposed to the public domain. Currently, anyone who can access the app can alter settings, making it a potential security risk.

## Proposed Features
1. **User Authentication:**  
   Introduce a simple authentication system that requires a username and password to access the web interface and manage settings.
   
2. **Role-Based Access Control (Optional):**  
   Implement different access levels (e.g., admin, viewer) to restrict who can change settings or only view the media library.

3. **Optional Two-Factor Authentication (2FA):**  
   To improve security further, I suggest including an option to enable 2FA (via apps like Google Authenticator (TOTP), or email) for users who want additional protection.

## Reasoning 
When using ErsatzTV in a public-facing environment (such as on a home server or cloud), the lack of authentication poses a significant security risk. Anyone with access to the web interface can modify crucial settings, which could lead to accidental or malicious changes. Adding authentication would protect against unauthorized access and ensure that only trusted users can configure and manage the app. Furthermore, implementing optional 2FA would add another layer of security for users who desire increased protection.

## Benefits
- Protects the app from unauthorized changes.
- adds security when facing the public internet.
- Provides peace of mind for users hosting their servers externally.

I think these changes would improve the security and usability of ErsatzTV, especially for users with public-facing servers.

**Comment by paul19920801** [comment]
I second this suggestion - and the consideration of implementing basic channel encryption & scrambling.

**Comment by jasongdove** [comment]
I have no plans to add user authentication or DRM directly to ETV. With that said, it is currently possible to secure both the admin UI and the streaming endpoints.

For the admin UI, OIDC can be used (e.g. Keycloak, Authelia, Auth0) with the following environment variables (note the double underscore separator `__`:
    - `OIDC__AUTHORITY`
    - `OIDC__CLIENTID`
    - `OIDC__CLIENTSECRET`
    - `OIDC__LOGOUTURI` (optional, needed for Auth0, use `https://{auth0-domain}/v2/logout?client_id={auth0-client-id}` with proper values for domain and client-id)

For the streaming endpoints, JWT can be used by configuring a signing key environment variable: `JWT__ISSUERSIGNINGKEY`. When configured, a JWT signed with the configured signing key is required to be passed in the query string as `access_token`, for example:
    - `http://localhost:8409/iptv/channels.m3u?access_token=ABCDEF`
    - `http://localhost:8409/iptv/xmltv.xml?access_token=ABCDEF`
