### ISSUE TITLE
Is it possible to stream more than one audio track?

### ISSUE THREAD

**Issue by carawan** [ErsatzTV/ErsatzTV#1923]
There is content with different audio track options. Is it possible to stream more than one track so that when viewing, you can select the desired one?

**Comment by jasongdove** [comment]
Generally speaking, no, ETV will only process a single audio track.

The only exception to this is using `HLS Direct` which will send all (unprocessed) audio tracks when the schedule item and channel have no preferred audio language and no preferred audio title. Note that `HLS Direct` does have significant limitations (from https://ersatztv.org/docs/user-guide/create-channels#streaming-mode)

> HLS Direct does not transcode content and can perform better on low power systems, but does not support watermarks and some clients will have issues at program boundaries
