### ISSUE TITLE
Unable to locate ffmpeg on MacOS

### ISSUE THREAD

**Issue by nothing2obvi** [ErsatzTV/ErsatzTV#1930]
I couldn't get ErsatzTV to work on Docker, so now I'm trying the Mac version, but I get this:

```
Unable to locate ffmpeg
```

ffmpeg is already installed on my Mac, via `brew install ffmpeg`.

I'd appreciate any help. Thanks.

**Comment by TheYakEmperor** [comment]
I have the same issue. Can't find any way to solve it.

**Comment by jasongdove** [comment]
FFmpeg is a dependency of ErsatzTV that is not included on MacOS. You need to install ffmpeg yourself (perhaps using something like `brew install ffmpeg`), and tell ETV where to find it (in ETV's main settings page.

**Comment by nothing2obvi** [comment]
Thank you!
