### ISSUE TITLE
Subtitles not displaying with matching preferred language or none

### ISSUE THREAD

**Issue by elgatopanzon** [ErsatzTV/ErsatzTV#1931]
Hello, I am aware of #1761 and this lead me in the direction to check the subtitle language, enable subtitle extraction, and then reset the playout.

The log indicates successful extraction of subtitles:

```
07/11/2024 19:01:03 -06:00	Debug	Done checking playouts [7] for text subtitles to extract
07/11/2024 19:01:03 -06:00	Debug	Successfully extracted 7 subtitles
07/11/2024 18:59:56 -06:00	Debug	Checking media items [1585] for text subtitles or fonts to extract for playouts [7]
07/11/2024 18:59:56 -06:00	Debug	Checking playouts [7] for text subtitles to extract
```

This is confirmed by checking the media info for the exact playing episode:

```
{
      "Index": 6,
      "Kind": "Subtitle",
      "Codec": "subrip",
      "Language": "eng",
      "FileName": "CD/04/CD0406274DF8913AD538479950135B18.srt",
      "IsExtracted": true
    },
    {
      "Index": 7,
      "Kind": "Subtitle",
      "Codec": "subrip",
      "Language": "eng",
      "FileName": "9C/0E/9C0E60F4E8D1EBA06F03E1BF8BA0BBE0.srt",
      "IsExtracted": true
    },
```

However when playing the channel, it still does not find the subtitles:

```
07/11/2024 19:04:11 -06:00	Debug	Preferred subtitle language has multiple codes ["eng","en"]
07/11/2024 19:04:11 -06:00	Debug	Found no subtitles for channel 1 with mode "Forced" matching language ["eng","en"]
```

The channel is set to only play this media item for testing this.

**Comment by jasongdove** [comment]
> Found no subtitles for channel 1 with mode "Forced" matching language ["eng","en"]

In addition to language metadata, subtitles have "default" and "forced" metadata flags (true/false). Your configuration is telling ETV to search for English subtitles with the "forced" metadata tag, which these do not have. There are two options to fix this:

1. Set the "forced" flag on the track you want using something like mkvpropedit
2. Change the subtitle mode to "default", which looks for the default flag, but will fall back to others if the flag is not found. Note that in this case, it will also prioritize the track with the lower index.

**Comment by elgatopanzon** [comment]
Ah I understand, I thought that meant it should force display of the subtitles. Now that I set it to "Any", the subtitles work!

Thanks a ton!
