### ISSUE TITLE
Issue Updating library (jellyfin linked)

### ISSUE THREAD

**Issue by Domjen2521** [ErsatzTV/ErsatzTV#1944]
on current version v0.8.8-fbb7a661-win-x64 the jellyfin library does not scrape correctly in ErsatzTV. It will only get one of the 3 shows added to the jellyfin library. I had performed regular and deep scan on the newest update to no avail.

I rolled back to v0.8.8-fdbd8a07-win-x64 and the system immediately scraped the two remaining shows from the jellyfin library without issue. i went back to the newer version afterwards and the information is present without updating. currently trying to add one more show and see if the issue occurs again on the new version.

**Comment by jasongdove** [comment]
Do you see any errors or other scanning messages in the logs? It will be hard to troubleshoot without any details about what might be going wrong.

**Comment by Domjen2521** [comment]
The only thing that seems to get my attention is that the search index fails to initialize.  please bear with me, i am going to clear logs and use the most recent version and see if i can replicate the error as before.


Logs
Message
11/19/2024 3:41:14 PM -06:00 	Information 	Successfully synchronized Jellyfin libraries for source 2
11/19/2024 3:41:14 PM -06:00 	Information 	Successfully synchronized Jellyfin admin user id for source 2
11/19/2024 3:41:13 PM -06:00 	Debug 	Scheduler sleeping for 19 minutes
11/19/2024 3:41:13 PM -06:00 	Information 	Successfully synchronized jellyfin media sources
11/19/2024 3:41:13 PM -06:00 	Information 	Scanner service started
11/19/2024 3:41:13 PM -06:00 	Information 	Plex service started; secrets are at C:\Users\Mingo Arcade\AppData\Local\ersatztv\plex-secrets.json
11/19/2024 3:41:13 PM -06:00 	Information 	Jellyfin service started; secrets are at C:\Users\Mingo Arcade\AppData\Local\ersatztv\jellyfin-secrets.json
11/19/2024 3:41:13 PM -06:00 	Information 	Emby service started; secrets are at C:\Users\Mingo Arcade\AppData\Local\ersatztv\emby-secrets.json
11/19/2024 3:41:13 PM -06:00 	Information 	Scheduler service started
11/19/2024 3:41:13 PM -06:00 	Information 	Done migrating search index in 23 seconds
11/19/2024 3:40:50 PM -06:00 	Information 	Done initializing search index
11/19/2024 3:40:50 PM -06:00 	Information 	Migrating search index to version 44
11/19/2024 3:40:50 PM -06:00 	Warning 	Search index failed to initialize; will delete and recreate
11/19/2024 3:40:49 PM -06:00 	Information 	Initializing search index
11/19/2024 3:40:49 PM -06:00 	Information 	Done cleaning database

11/19/2024 3:40:49 PM -06:00 	Information 	Located ffprobe at C:\ErsatzTV\ffprobe.exe
11/19/2024 3:40:49 PM -06:00 	Information 	Located ffmpeg at C:\ErsatzTV\ffmpeg.exe
11/19/2024 3:40:49 PM -06:00 	Information 	Done emptying transcode cache folder
11/19/2024 3:40:49 PM -06:00 	Information 	Cleaning channel cache
11/19/2024 3:40:49 PM -06:00 	Information 	Emptying transcode cache folder
11/19/2024 3:40:49 PM -06:00 	Information 	Search index worker service started
11/19/2024 3:40:49 PM -06:00 	Information 	Done applying database migrations
11/19/2024 3:40:49 PM -06:00 	Information 	Cleaning database
11/19/2024 3:40:47 PM -06:00 	Information 	FFmpeg worker service started
11/19/2024 3:40:47 PM -06:00 	Information 	Worker service started
11/19/2024 3:40:47 PM -06:00 	Information 	Server will listen on port 8409 - try UI at http://localhost:8409
11/19/2024 3:40:47 PM -06:00 	Information 	Applying database migrations
11/19/2024 3:40:47 PM -06:00 	Information 	Using Lucene (embedded) search index backend
11/19/2024 3:40:47 PM -06:00 	Information 	Transcode folder is C:\Users\Mingo Arcade\AppData\Local\etv-transcode
11/19/2024 3:40:47 PM -06:00 	Information 	Database is at C:\Users\Mingo Arcade\AppData\Local\ersatztv\ersatztv.sqlite3
11/19/2024 3:40:47 PM -06:00 	Warning 	Give feedback at https://github.com/ErsatzTV/ErsatzTV or https://discord.gg/hHaJm3yGy6
11/19/2024 3:40:47 PM -06:00 	Warning 	This is beta software and may be unstable
11/19/2024 3:40:47 PM -06:00 	Information 	ErsatzTV version v0.8.8-fdbd8a07-win-x64
11/19/2024 3:39:55 PM -06:00 	Debug 	Search query parsed from [type:image AND ("you wish")] to [+type:image +(title:"you wish")]
11/19/2024 3:39:55 PM -06:00 	Debug 	Search query parsed from [type:artist AND ("you wish")] to [+type:artist +(title:"you wish")]
11/19/2024 3:39:55 PM -06:00 	Debug 	Search query parsed from [type:image AND ("you wish")] to [+type:image +(title:"you wish")]
11/19/2024 3:39:55 PM -06:00 	Debug 	Search query parsed from [type:song AND ("you wish")] to [+type:song +(title:"you wish")]
11/19/2024 3:39:55 PM -06:00 	Debug 	Search query parsed from [type:other_video AND ("you wish")] to [+type:other_video +(title:"you wish")]
11/19/2024 3:39:55 PM -06:00 	Debug 	Search query parsed from [type:music_video AND ("you wish")] to [+type:music_video +(title:"you wish")]
11/19/2024 3:39:55 PM -06:00 	Debug 	Search query parsed from [type:episode AND ("you wish")] to [+type:episode +(title:"you wish")]
11/19/2024 3:39:55 PM -06:00 	Debug 	Search query parsed from [type:season AND ("you wish")] to [+type:season +(title:"you wish")]
11/19/2024 3:39:55 PM -06:00 	Debug 	Search query parsed from [type:show AND ("you wish")] to [+type:show +(title:"you wish")]
11/19/2024 3:39:55 PM -06:00 	Debug 	Search query parsed from [type:movie AND ("you wish")] to [+type:movie +(title:"you wish")]
11/19/2024 3:39:51 PM -06:00 	Debug 	Search query parsed from [type:image AND ("teen angel")] to [+type:image +(title:"teen angel")]
11/19/2024 3:39:51 PM -06:00 	Debug 	Search query parsed from [type:artist AND ("teen angel")] to [+type:artist +(title:"teen angel")]
11/19/2024 3:39:51 PM -06:00 	Debug 	Search query parsed from [type:image AND ("teen angel")] to [+type:image +(title:"teen angel")]
11/19/2024 3:39:51 PM -06:00 	Debug 	Search query parsed from [type:song AND ("teen angel")] to [+type:song +(title:"teen angel")]
11/19/2024 3:39:51 PM -06:00 	Debug 	Search query parsed from [type:other_video AND ("teen angel")] to [+type:other_video +(title:"teen angel")]
11/19/2024 3:39:51 PM -06:00 	Debug 	Search query parsed from [type:music_video AND ("teen angel")] to [+type:music_video +(title:"teen angel")]
11/19/2024 3:39:51 PM -06:00 	Debug 	Search query parsed from [type:episode AND ("teen angel")] to [+type:episode +(title:"teen angel")]
11/19/2024 3:39:51 PM -06:00 	Debug 	Search query parsed from [type:season AND ("teen angel")] to [+type:season +(title:"teen angel")]
11/19/2024 3:39:51 PM -06:00 	Debug 	Search query parsed from [type:show AND ("teen angel")] to [+type:show +(title:"teen angel")]
11/19/2024 3:39:51 PM -06:00 	Debug 	Search query parsed from [type:movie AND ("teen angel")] to [+type:movie +(title:"teen angel")]
11/19/2024 3:39:42 PM -06:00 	Debug 	Search query parsed from [type:image AND (teen angel)] to [+type:image +((title:teen) (title:angel))]
11/19/2024 3:39:42 PM -06:00 	Debug 	Search query parsed from [type:artist AND (teen angel)] to [+type:artist +((title:teen) (title:angel))]
11/19/2024 3:39:42 PM -06:00 	Debug 	Search query parsed from [type:image AND (teen angel)] to [+type:image +((title:teen) (title:angel))]
11/19/2024 3:39:42 PM -06:00 	Debug 	Search query parsed from [type:song AND (teen angel)] to [+type:song +((title:teen) (title:angel))]
11/19/2024 3:39:42 PM -06:00 	Debug 	Search query parsed from [type:other_video AND (teen angel)] to [+type:other_video +((title:teen) (title:angel))]
11/19/2024 3:39:42 PM -06:00 	Debug 	Search query parsed from [type:music_video AND (teen angel)] to [+type:music_video +((title:teen) (title:angel))]
11/19/2024 3:39:42 PM -06:00 	Debug 	Search query parsed from [type:episode AND (teen angel)] to [+type:episode +((title:teen) (title:angel))]
11/19/2024 3:39:42 PM -06:00 	Debug 	Search query parsed from [type:season AND (teen angel)] to [+type:season +((title:teen) (title:angel))]
11/19/2024 3:39:42 PM -06:00 	Debug 	Search query parsed from [type:show AND (teen angel)] to [+type:show +((title:teen) (title:angel))]
11/19/2024 3:39:42 PM -06:00 	Debug 	Search query parsed from [type:movie AND (teen angel)] to [+type:movie +((title:teen) (title:angel))]
11/19/2024 3:30:54 PM -06:00 	Information 	Successfully synchronized Jellyfin libraries for source 2
11/19/2024 3:30:51 PM -06:00 	Debug 	Completed garbage collection

**Comment by Domjen2521** [comment]
I have added a show called Voyagers! (1982). it added it, however it doesnt list it correctly when searching. instead listing it as one episode as voyagers episode 15. when i click on it, it shows the entire list of episodes and can scroll it. here is the logs.






11/19/2024 6:06:41 PM -06:00 	Debug 	Search query parsed from [type:image AND (tv show = voyagers)] to [+type:image +((title:tv) (title:show) (title:=) (title:voyagers))]
11/19/2024 6:06:40 PM -06:00 	Debug 	Search query parsed from [type:artist AND (tv show = voyagers)] to [+type:artist +((title:tv) (title:show) (title:=) (title:voyagers))]
11/19/2024 6:06:40 PM -06:00 	Debug 	Search query parsed from [type:image AND (tv show = voyagers)] to [+type:image +((title:tv) (title:show) (title:=) (title:voyagers))]
11/19/2024 6:06:40 PM -06:00 	Debug 	Search query parsed from [type:song AND (tv show = voyagers)] to [+type:song +((title:tv) (title:show) (title:=) (title:voyagers))]
11/19/2024 6:06:40 PM -06:00 	Debug 	Search query parsed from [type:other_video AND (tv show = voyagers)] to [+type:other_video +((title:tv) (title:show) (title:=) (title:voyagers))]
11/19/2024 6:06:40 PM -06:00 	Debug 	Search query parsed from [type:music_video AND (tv show = voyagers)] to [+type:music_video +((title:tv) (title:show) (title:=) (title:voyagers))]
11/19/2024 6:06:40 PM -06:00 	Debug 	Search query parsed from [type:episode AND (tv show = voyagers)] to [+type:episode +((title:tv) (title:show) (title:=) (title:voyagers))]
11/19/2024 6:06:40 PM -06:00 	Debug 	Search query parsed from [type:season AND (tv show = voyagers)] to [+type:season +((title:tv) (title:show) (title:=) (title:voyagers))]
11/19/2024 6:06:40 PM -06:00 	Debug 	Search query parsed from [type:show AND (tv show = voyagers)] to [+type:show +((title:tv) (title:show) (title:=) (title:voyagers))]
11/19/2024 6:06:40 PM -06:00 	Debug 	Search query parsed from [type:movie AND (tv show = voyagers)] to [+type:movie +((title:tv) (title:show) (title:=) (title:voyagers))]
11/19/2024 6:06:07 PM -06:00 	Debug 	Search query parsed from [type:image AND ("voyagers")] to [+type:image +(title:voyagers)]
11/19/2024 6:06:07 PM -06:00 	Debug 	Search query parsed from [type:artist AND ("voyagers")] to [+type:artist +(title:voyagers)]
11/19/2024 6:06:06 PM -06:00 	Debug 	Search query parsed from [type:image AND ("voyagers")] to [+type:image +(title:voyagers)]
11/19/2024 6:06:06 PM -06:00 	Debug 	Search query parsed from [type:song AND ("voyagers")] to [+type:song +(title:voyagers)]
11/19/2024 6:06:06 PM -06:00 	Debug 	Search query parsed from [type:other_video AND ("voyagers")] to [+type:other_video +(title:voyagers)]
11/19/2024 6:06:06 PM -06:00 	Debug 	Search query parsed from [type:music_video AND ("voyagers")] to [+type:music_video +(title:voyagers)]
11/19/2024 6:06:06 PM -06:00 	Debug 	Search query parsed from [type:episode AND ("voyagers")] to [+type:episode +(title:voyagers)]
11/19/2024 6:06:06 PM -06:00 	Debug 	Search query parsed from [type:season AND ("voyagers")] to [+type:season +(title:voyagers)]
11/19/2024 6:06:06 PM -06:00 	Debug 	Search query parsed from [type:show AND ("voyagers")] to [+type:show +(title:voyagers)]
11/19/2024 6:06:06 PM -06:00 	Debug 	Search query parsed from [type:movie AND ("voyagers")] to [+type:movie +(title:voyagers)]
11/19/2024 6:05:45 PM -06:00 	Debug 	Search query parsed from [type:image AND (voyagers)] to [+type:image +(title:voyagers)]
11/19/2024 6:05:45 PM -06:00 	Debug 	Search query parsed from [type:artist AND (voyagers)] to [+type:artist +(title:voyagers)]
11/19/2024 6:05:45 PM -06:00 	Debug 	Search query parsed from [type:image AND (voyagers)] to [+type:image +(title:voyagers)]
11/19/2024 6:05:45 PM -06:00 	Debug 	Search query parsed from [type:song AND (voyagers)] to [+type:song +(title:voyagers)]
11/19/2024 6:05:45 PM -06:00 	Debug 	Search query parsed from [type:other_video AND (voyagers)] to [+type:other_video +(title:voyagers)]
11/19/2024 6:05:45 PM -06:00 	Debug 	Search query parsed from [type:music_video AND (voyagers)] to [+type:music_video +(title:voyagers)]
11/19/2024 6:05:45 PM -06:00 	Debug 	Search query parsed from [type:episode AND (voyagers)] to [+type:episode +(title:voyagers)]
11/19/2024 6:05:45 PM -06:00 	Debug 	Search query parsed from [type:season AND (voyagers)] to [+type:season +(title:voyagers)]
11/19/2024 6:05:45 PM -06:00 	Debug 	Search query parsed from [type:show AND (voyagers)] to [+type:show +(title:voyagers)]
11/19/2024 6:05:45 PM -06:00 	Debug 	Search query parsed from [type:movie AND (voyagers)] to [+type:movie +(title:voyagers)]
11/19/2024 6:04:31 PM -06:00 	Debug 	Search query parsed from [type:image AND (voyagers)] to [+type:image +(title:voyagers)]
11/19/2024 6:04:31 PM -06:00 	Debug 	Search query parsed from [type:artist AND (voyagers)] to [+type:artist +(title:voyagers)]
11/19/2024 6:04:31 PM -06:00 	Debug 	Search query parsed from [type:image AND (voyagers)] to [+type:image +(title:voyagers)]
11/19/2024 6:04:31 PM -06:00 	Debug 	Search query parsed from [type:song AND (voyagers)] to [+type:song +(title:voyagers)]
11/19/2024 6:04:31 PM -06:00 	Debug 	Search query parsed from [type:other_video AND (voyagers)] to [+type:other_video +(title:voyagers)]
11/19/2024 6:04:31 PM -06:00 	Debug 	Search query parsed from [type:music_video AND (voyagers)] to [+type:music_video +(title:voyagers)]
11/19/2024 6:04:31 PM -06:00 	Debug 	Search query parsed from [type:episode AND (voyagers)] to [+type:episode +(title:voyagers)]
11/19/2024 6:04:31 PM -06:00 	Debug 	Search query parsed from [type:season AND (voyagers)] to [+type:season +(title:voyagers)]
11/19/2024 6:04:31 PM -06:00 	Debug 	Search query parsed from [type:show AND (voyagers)] to [+type:show +(title:voyagers)]
11/19/2024 6:04:31 PM -06:00 	Debug 	Search query parsed from [type:movie AND (voyagers)] to [+type:movie +(title:voyagers)]
11/19/2024 6:03:46 PM -06:00 	Debug 	Completed garbage collection
11/19/2024 6:03:45 PM -06:00 	Debug 	Starting garbage collection
11/19/2024 6:03:45 PM -06:00 	Debug 	Refreshing channel data (XMLTV) for channel 105
11/19/2024 6:03:45 PM -06:00 	Debug 	Refreshing channel data (XMLTV) for channel 102
11/19/2024 6:03:45 PM -06:00 	Debug 	Refreshing channel data (XMLTV) for channel 100
11/19/2024 6:03:45 PM -06:00 	Debug 	Refreshing channel data (XMLTV) for channel 88.3
11/19/2024 6:03:45 PM -06:00 	Debug 	Refreshing channel data (XMLTV) for channel 88.2
11/19/2024 6:03:45 PM -06:00 	Debug 	Refreshing channel data (XMLTV) for channel 83.4
11/19/2024 6:03:45 PM -06:00 	Debug 	Refreshing channel data (XMLTV) for channel 83.3
11/19/2024 6:03:45 PM -06:00 	Debug 	Refreshing channel data (XMLTV) for channel 83.2
11/19/2024 6:03:45 PM -06:00 	Debug 	Refreshing channel data (XMLTV) for channel 83
11/19/2024 6:03:45 PM -06:00 	Debug 	Refreshing channel data (XMLTV) for channel 81.4
11/19/2024 6:03:45 PM -06:00 	Debug 	Refreshing channel data (XMLTV) for channel 81.3
11/19/2024 6:03:45 PM -06:00 	Debug 	Refreshing channel data (XMLTV) for channel 81.2
11/19/2024 6:03:45 PM -06:00 	Debug 	Refreshing channel data (XMLTV) for channel 81
11/19/2024 6:03:44 PM -06:00 	Debug 	Refreshing channel data (XMLTV) for channel 59
11/19/2024 6:03:44 PM -06:00 	Debug 	Refreshing channel data (XMLTV) for channel 57
11/19/2024 6:03:44 PM -06:00 	Debug 	Refreshing channel data (XMLTV) for channel 56.8
11/19/2024 6:03:44 PM -06:00 	Debug 	Refreshing channel data (XMLTV) for channel 56.3
11/19/2024 6:03:44 PM -06:00 	Debug 	Refreshing channel data (XMLTV) for channel 51.2
11/19/2024 6:03:44 PM -06:00 	Debug 	Refreshing channel data (XMLTV) for channel 51
11/19/2024 6:03:44 PM -06:00 	Debug 	Refreshing channel data (XMLTV) for channel 37
11/19/2024 6:03:44 PM -06:00 	Debug 	Refreshing channel data (XMLTV) for channel 36.2
11/19/2024 6:03:44 PM -06:00 	Debug 	Refreshing channel data (XMLTV) for channel 29
11/19/2024 6:03:43 PM -06:00 	Debug 	Refreshing channel data (XMLTV) for channel 22
11/19/2024 6:03:43 PM -06:00 	Debug 	Refreshing channel data (XMLTV) for channel 19.2
11/19/2024 6:03:43 PM -06:00 	Debug 	Refreshing channel data (XMLTV) for channel 19
11/19/2024 6:03:43 PM -06:00 	Debug 	Refreshing channel data (XMLTV) for channel 18.2
11/19/2024 6:03:43 PM -06:00 	Debug 	Refreshing channel data (XMLTV) for channel 13
11/19/2024 6:03:43 PM -06:00 	Debug 	Refreshing channel data (XMLTV) for channel 10
11/19/2024 6:03:43 PM -06:00 	Debug 	Refreshing channel data (XMLTV) for channel 8
11/19/2024 6:03:43 PM -06:00 	Debug 	Refreshing channel data (XMLTV) for channel 7.2
11/19/2024 6:03:42 PM -06:00 	Debug 	Refreshing channel data (XMLTV) for channel 2.4
11/19/2024 6:03:42 PM -06:00 	Debug 	Completed garbage collection
11/19/2024 6:03:42 PM -06:00 	Debug 	Starting garbage collection
11/19/2024 6:03:42 PM -06:00 	Debug 	Built playout 123
11/19/2024 6:03:42 PM -06:00 	Debug 	Built playout 122
11/19/2024 6:03:42 PM -06:00 	Debug 	Built playout 45
11/19/2024 6:03:42 PM -06:00 	Debug 	Built playout 104
11/19/2024 6:03:41 PM -06:00 	Debug 	Built playout 70
11/19/2024 6:03:41 PM -06:00 	Debug 	Built playout 10
11/19/2024 6:03:41 PM -06:00 	Debug 	Built playout 62
11/19/2024 6:03:41 PM -06:00 	Debug 	Built playout 63
11/19/2024 6:03:40 PM -06:00 	Debug 	Built playout 61
11/19/2024 6:03:40 PM -06:00 	Debug 	Built playout 110
11/19/2024 6:03:40 PM -06:00 	Debug 	Built playout 60
11/19/2024 6:03:40 PM -06:00 	Debug 	Built playout 59
11/19/2024 6:03:40 PM -06:00 	Debug 	Built playout 149
11/19/2024 6:03:39 PM -06:00 	Debug 	Built playout 175
11/19/2024 6:03:39 PM -06:00 	Debug 	Built playout 105
11/19/2024 6:03:39 PM -06:00 	Debug 	Built playout 80
11/19/2024 6:03:39 PM -06:00 	Debug 	Built playout 58
11/19/2024 6:03:38 PM -06:00 	Debug 	Built playout 14
11/19/2024 6:03:38 PM -06:00 	Debug 	Built playout 73
11/19/2024 6:03:38 PM -06:00 	Debug 	Built playout 31
11/19/2024 6:03:38 PM -06:00 	Debug 	Built playout 75
11/19/2024 6:03:38 PM -06:00 	Debug 	Built playout 13
11/19/2024 6:03:37 PM -06:00 	Debug 	Built playout 133
11/19/2024 6:03:37 PM -06:00 	Debug 	Built playout 180
11/19/2024 6:03:37 PM -06:00 	Debug 	Built playout 176
11/19/2024 6:03:37 PM -06:00 	Debug 	Built playout 169
11/19/2024 6:03:37 PM -06:00 	Debug 	Built playout 168
11/19/2024 6:03:36 PM -06:00 	Debug 	Built playout 167
11/19/2024 6:03:36 PM -06:00 	Debug 	Built playout 173
11/19/2024 6:03:36 PM -06:00 	Debug 	Built playout 172
11/19/2024 6:03:36 PM -06:00 	Debug 	Built playout 171
11/19/2024 6:03:35 PM -06:00 	Debug 	Built playout 170
11/19/2024 6:03:35 PM -06:00 	Debug 	Built playout 46
11/19/2024 6:03:35 PM -06:00 	Debug 	Built playout 195
11/19/2024 6:03:35 PM -06:00 	Debug 	Built playout 51
11/19/2024 6:03:34 PM -06:00 	Debug 	Built playout 50
11/19/2024 6:03:34 PM -06:00 	Debug 	Built playout 49
11/19/2024 6:03:34 PM -06:00 	Debug 	Built playout 48
11/19/2024 6:03:34 PM -06:00 	Debug 	Built playout 47
11/19/2024 6:03:33 PM -06:00 	Debug 	Built playout 93
11/19/2024 6:03:33 PM -06:00 	Debug 	Built playout 22
11/19/2024 6:03:33 PM -06:00 	Debug 	Built playout 119
11/19/2024 6:03:33 PM -06:00 	Debug 	Built playout 186
11/19/2024 6:03:32 PM -06:00 	Debug 	Built playout 155
11/19/2024 6:03:32 PM -06:00 	Debug 	Built playout 57
11/19/2024 6:03:32 PM -06:00 	Debug 	Built playout 56
11/19/2024 6:03:32 PM -06:00 	Debug 	Built playout 55
11/19/2024 6:03:31 PM -06:00 	Debug 	Built playout 54
11/19/2024 6:03:31 PM -06:00 	Debug 	Built playout 53
11/19/2024 6:03:31 PM -06:00 	Debug 	Built playout 52
11/19/2024 6:03:31 PM -06:00 	Debug 	Built playout 185
11/19/2024 6:03:30 PM -06:00 	Debug 	Built playout 184
11/19/2024 6:03:30 PM -06:00 	Debug 	Built playout 24
11/19/2024 6:03:30 PM -06:00 	Debug 	Built playout 43
11/19/2024 6:03:30 PM -06:00 	Debug 	Built playout 42
11/19/2024 6:03:30 PM -06:00 	Debug 	Built playout 86
11/19/2024 6:03:29 PM -06:00 	Debug 	Built playout 88
11/19/2024 6:03:29 PM -06:00 	Debug 	Built playout 87
11/19/2024 6:03:29 PM -06:00 	Debug 	Built playout 84
11/19/2024 6:03:29 PM -06:00 	Debug 	Built playout 151
11/19/2024 6:03:28 PM -06:00 	Debug 	Built playout 144
11/19/2024 6:03:28 PM -06:00 	Debug 	Built playout 76
11/19/2024 6:03:28 PM -06:00 	Debug 	Built playout 181
11/19/2024 6:03:28 PM -06:00 	Debug 	Built playout 198
11/19/2024 6:03:27 PM -06:00 	Debug 	Built playout 23
11/19/2024 6:03:27 PM -06:00 	Debug 	Built playout 150
11/19/2024 6:03:27 PM -06:00 	Debug 	Built playout 145
11/19/2024 6:03:27 PM -06:00 	Debug 	Built playout 19
11/19/2024 6:03:26 PM -06:00 	Debug 	Built playout 202
11/19/2024 6:03:26 PM -06:00 	Debug 	Built playout 200
11/19/2024 6:03:26 PM -06:00 	Debug 	Built playout 204
11/19/2024 6:03:26 PM -06:00 	Debug 	Built playout 199
11/19/2024 6:03:25 PM -06:00 	Debug 	Built playout 166
11/19/2024 6:03:25 PM -06:00 	Debug 	Built playout 165
11/19/2024 6:03:25 PM -06:00 	Debug 	Built playout 164
11/19/2024 6:03:24 PM -06:00 	Debug 	Built playout 163
11/19/2024 6:03:24 PM -06:00 	Debug 	Built playout 162
11/19/2024 6:03:24 PM -06:00 	Debug 	Built playout 161
11/19/2024 6:03:24 PM -06:00 	Debug 	Built playout 160
11/19/2024 6:03:23 PM -06:00 	Information 	Successfully synchronized Jellyfin libraries for source 2
11/19/2024 6:03:23 PM -06:00 	Debug 	Built playout 159
11/19/2024 6:03:23 PM -06:00 	Debug 	Built playout 158
11/19/2024 6:03:23 PM -06:00 	Debug 	Built playout 190
11/19/2024 6:03:23 PM -06:00 	Debug 	Built playout 189
11/19/2024 6:03:22 PM -06:00 	Debug 	Built playout 40
11/19/2024 6:03:22 PM -06:00 	Debug 	Built playout 38
11/19/2024 6:03:22 PM -06:00 	Debug 	Built playout 25
11/19/2024 6:03:22 PM -06:00 	Debug 	Built playout 103
11/19/2024 6:03:21 PM -06:00 	Debug 	Built playout 102
11/19/2024 6:03:21 PM -06:00 	Debug 	Built playout 39
11/19/2024 6:03:21 PM -06:00 	Debug 	Built playout 41
11/19/2024 6:03:20 PM -06:00 	Debug 	Built playout 36
11/19/2024 6:03:20 PM -06:00 	Debug 	Built playout 37
11/19/2024 6:03:20 PM -06:00 	Debug 	Built playout 35
11/19/2024 6:03:19 PM -06:00 	Debug 	Built playout 33
11/19/2024 6:03:19 PM -06:00 	Debug 	Built playout 32
11/19/2024 6:03:18 PM -06:00 	Debug 	Built playout 136
11/19/2024 6:03:18 PM -06:00 	Debug 	Built playout 135
11/19/2024 6:03:18 PM -06:00 	Debug 	Built playout 101
11/19/2024 6:03:17 PM -06:00 	Debug 	Built playout 26
11/19/2024 6:03:17 PM -06:00 	Debug 	Built playout 193
11/19/2024 6:03:17 PM -06:00 	Debug 	Built playout 134
11/19/2024 6:03:17 PM -06:00 	Debug 	Built playout 78
11/19/2024 6:03:17 PM -06:00 	Debug 	Built playout 27
11/19/2024 6:03:16 PM -06:00 	Debug 	Built playout 30
11/19/2024 6:03:16 PM -06:00 	Debug 	Built playout 29
11/19/2024 6:03:16 PM -06:00 	Debug 	Built playout 28
11/19/2024 6:03:16 PM -06:00 	Debug 	Built playout 83
11/19/2024 6:03:15 PM -06:00 	Debug 	Built playout 82
11/19/2024 6:03:15 PM -06:00 	Debug 	Built playout 157
11/19/2024 6:03:15 PM -06:00 	Debug 	Built playout 156
11/19/2024 6:03:15 PM -06:00 	Debug 	Built playout 77
11/19/2024 6:03:14 PM -06:00 	Debug 	Built playout 188
11/19/2024 6:03:14 PM -06:00 	Debug 	Built playout 111
11/19/2024 6:03:14 PM -06:00 	Debug 	Built playout 154
11/19/2024 6:03:14 PM -06:00 	Debug 	Built playout 153
11/19/2024 6:03:13 PM -06:00 	Debug 	Built playout 132
11/19/2024 6:03:13 PM -06:00 	Debug 	Built playout 183
11/19/2024 6:03:13 PM -06:00 	Debug 	Built playout 18
11/19/2024 6:03:13 PM -06:00 	Debug 	Built playout 174
11/19/2024 6:03:12 PM -06:00 	Debug 	Built playout 17
11/19/2024 6:03:12 PM -06:00 	Debug 	Built playout 187
11/19/2024 6:03:12 PM -06:00 	Debug 	Built playout 179
11/19/2024 6:03:12 PM -06:00 	Debug 	Built playout 16
11/19/2024 6:03:11 PM -06:00 	Debug 	Built playout 8
11/19/2024 6:03:11 PM -06:00 	Debug 	Built playout 143
11/19/2024 6:03:11 PM -06:00 	Debug 	Built playout 117
11/19/2024 6:03:10 PM -06:00 	Debug 	Built playout 142
11/19/2024 6:03:10 PM -06:00 	Debug 	Built playout 12
11/19/2024 6:03:09 PM -06:00 	Debug 	Built playout 148
11/19/2024 6:03:09 PM -06:00 	Debug 	Built playout 92
11/19/2024 6:03:09 PM -06:00 	Debug 	Built playout 147
11/19/2024 6:03:08 PM -06:00 	Debug 	Built playout 91
11/19/2024 6:03:08 PM -06:00 	Debug 	Built playout 146
11/19/2024 6:03:08 PM -06:00 	Debug 	Built playout 131
11/19/2024 6:03:07 PM -06:00 	Debug 	Built playout 90
11/19/2024 6:03:07 PM -06:00 	Debug 	Built playout 141
11/19/2024 6:03:06 PM -06:00 	Debug 	Built playout 116
11/19/2024 6:03:06 PM -06:00 	Debug 	Built playout 140
11/19/2024 6:03:06 PM -06:00 	Debug 	Built playout 89
11/19/2024 6:03:05 PM -06:00 	Debug 	Built playout 139
11/19/2024 6:03:05 PM -06:00 	Debug 	Built playout 115
11/19/2024 6:03:05 PM -06:00 	Debug 	Built playout 137
11/19/2024 6:03:03 PM -06:00 	Information 	Successfully synchronized Jellyfin libraries for source 2
11/19/2024 6:03:03 PM -06:00 	Information 	Successfully synchronized Jellyfin admin user id for source 2
11/19/2024 6:03:03 PM -06:00 	Debug 	Scheduler sleeping for 27 minutes
11/19/2024 6:03:03 PM -06:00 	Information 	Successfully synchronized jellyfin media sources
11/19/2024 6:03:03 PM -06:00 	Information 	Jellyfin service started; secrets are at C:\Users\Mingo Arcade\AppData\Local\ersatztv\jellyfin-secrets.json
11/19/2024 6:03:03 PM -06:00 	Information 	Emby service started; secrets are at C:\Users\Mingo Arcade\AppData\Local\ersatztv\emby-secrets.json
11/19/2024 6:03:03 PM -06:00 	Information 	Plex service started; secrets are at C:\Users\Mingo Arcade\AppData\Local\ersatztv\plex-secrets.json
11/19/2024 6:03:03 PM -06:00 	Information 	Scheduler service started
11/19/2024 6:03:03 PM -06:00 	Information 	Scanner service started
11/19/2024 6:03:03 PM -06:00 	Information 	Search index is already version 44
11/19/2024 6:03:01 PM -06:00 	Information 	Done initializing search index
11/19/2024 6:03:01 PM -06:00 	Information 	Located ffprobe at C:\ErsatzTV\ffprobe.exe
11/19/2024 6:03:01 PM -06:00 	Information 	Initializing search index
11/19/2024 6:03:01 PM -06:00 	Information 	Done cleaning database
11/19/2024 6:03:01 PM -06:00 	Information 	Located ffmpeg at C:\ErsatzTV\ffmpeg.exe
11/19/2024 6:03:01 PM -06:00 	Information 	Search index worker service started
11/19/2024 6:03:01 PM -06:00 	Information 	Done emptying transcode cache folder
11/19/2024 6:03:01 PM -06:00 	Information 	Cleaning channel cache
11/19/2024 6:03:01 PM -06:00 	Information 	Emptying transcode cache folder
11/19/2024 6:03:01 PM -06:00 	Information 	Done applying database migrations
11/19/2024 6:03:01 PM -06:00 	Information 	Cleaning database
11/19/2024 6:02:59 PM -06:00 	Information 	FFmpeg worker service started
11/19/2024 6:02:59 PM -06:00 	Information 	Worker service started
11/19/2024 6:02:59 PM -06:00 	Information 	Server will listen on port 8409 - try UI at http://localhost:8409
11/19/2024 6:02:59 PM -06:00 	Information 	Applying database migrations
11/19/2024 6:02:59 PM -06:00 	Information 	Using Lucene (embedded) search index backend
11/19/2024 6:02:58 PM -06:00 	Information 	Transcode folder is C:\Users\Mingo Arcade\AppData\Local\etv-transcode
11/19/2024 6:02:58 PM -06:00 	Information 	Database is at C:\Users\Mingo Arcade\AppData\Local\ersatztv\ersatztv.sqlite3
11/19/2024 6:02:58 PM -06:00 	Warning 	Give feedback at https://github.com/ErsatzTV/ErsatzTV or https://discord.gg/hHaJm3yGy6
11/19/2024 6:02:58 PM -06:00 	Warning 	This is beta software and may be unstable
11/19/2024 6:02:58 PM -06:00 	Information 	ErsatzTV version v0.8.8-fbb7a661-win-x64

**Comment by Domjen2521** [comment]
Could not replicate issue after multiple attempts. closing out listed issue, if reoccurs will open back up with logs.
