### ISSUE TITLE
Preferred Audio Option

### ISSUE THREAD

**Issue by Artiume** [ErsatzTV/ErsatzTV#291]
I've noticed that with files with dual audio, it defaults to the first audio track. The ability to have a preferred language option in the settings would be nice. I'm using Jellyfin and it'd be nice if it synced it via the metadata sync but I'm not sure if that'd be feasible or not.

**Comment by jasongdove** [comment]
There are two preferred language settings: one global setting in the `Settings` page, and one for each channel to override the global setting.

**Comment by Artiume** [comment]
ah gotcha. So it looks like the global isn't working for me and I must use the local channel audio preference

**Comment by jasongdove** [comment]
Also note that if your channels are configured as `HLS Direct` all audio streams will be sent to allow the client to select the desired stream. Stream selection using the preferred language is only performed when transcoding is used in either `MPEG-TS` or `HLS Hybrid` modes.

**Comment by Artiume** [comment]
Hmm, so in all 3 modes, setting the local channel preference to English worked, even in HLS-Direct mode. I was just testing one video so I'll need to test it some more.

**Comment by jasongdove** [comment]
I just double checked the code and it's a little more nuanced than I thought. HLS Direct will ignore the global language preference, but not the channel preference, so if you were using HLS Direct originally that might explain the behavior you observed. The logs should also give some clues.

**Comment by Artiume** [comment]
Yeah, I'm using Direct for my channels
