### ISSUE TITLE
normalize video option causes green filter on some episodes

### ISSUE THREAD

**Issue by nickyg666** [ErsatzTV/ErsatzTV#466]
If I turn normalize video off, I get no audio. I have tried aac, ac3 and mp3 audio codecs to no avail. How can I get rid of the green? it's difficult to discern exactly what media type is causing this, but it will work fine without normalize option, just with no audio. I know it's a "me" problem, but will gladly contribute logs or whatever else I can to help. Love the progress you've made in such a short period of time.

**Comment by jasongdove** [comment]
Could use a few more details to dig into these issues:
- Which hardware acceleration method and video codec is the ffmpeg profile using?
- Which streaming mode is the channel using?
- Which IPTV client is being used to watch the content?

**Comment by nickyg666** [comment]
Stream mode: MPEG-TS
HW acc: vaapi, hevc_vaapi on rx 460
watching on jellyfin livetv.
HLS has very mixed results with my library

**Comment by jasongdove** [comment]
Thanks for the info. VAAPI with AMD is definitely the least tested combination, but I do have an older card around that I'll do some testing with.

**Comment by nickyg666** [comment]
if you need anything else I'll gladly provide!
thanks!

**Comment by nickyg666** [comment]
testing these settings now only with files imported via PLEX library, will report back in A.M. whether or not it is a jellyfin/local library issue, as i've been having issues with those finding all my media, and thought maybe I will have different results with plex libraries. keeping hevc 1080p vaapi/radeonsi profile active during testing, as well as mpeg-ts (plex just throws various errors when viewing these stations). I'm thinking it could very well be a jellyfin issue as their roku app is in beta at best

**Comment by jasongdove** [comment]
My main development workstation is now VAAPI/AMD, and there have been many improvements to the VAAPI pipeline in the past couple of years. Please open a new issue if you have problems with the latest version of ETV.
