### ISSUE TITLE
In app guide 

### ISSUE THREAD

**Issue by binarygeek119** [ErsatzTV/ErsatzTV#563]
have you considered adding a guide in app right now i setup a channel and have to refresh emby's tv guide to see if i have it configured right for the channel would be nice if i could get a quick look in app. I was hoping for a guide like dizquetv has. If you add this I be so happy as this is the one thing I miss from dizquetv

**Comment by simcop2387** [comment]
Not sure if it existed when you wrote this, but you can view the planned schedule in the Playout section right now with 5.1 beta

**Comment by jasongdove** [comment]
I don't plan on adding this feature to ErsatzTV at this time.

If you use chrome, this extension might be what you're looking for https://chromewebstore.google.com/detail/epg-viewer/lnhfllpjnichiepbkgnfhpaakhicbelh
