### ISSUE TITLE
Stuck at starting HLS session for channel 1

### ISSUE THREAD

**Issue by Fallenbagel** [ErsatzTV/ErsatzTV#699]
I tried this and it worked once but I deleted that channel and made a new one as that was for just checking and the guide was messed up. However, after creating a new channel, whenever I try to start the channel it just says starting HLS session for channel 1 indefinitely.

**Comment by Domjen2521** [comment]
Are you doing HLS as direct or segmented? i noticed when i was first learning this software that the deleting and recreating channels can cause issues when changing the aspect ratio. Are you using a device or an app like tivimate. when i was first attempting this, i was using a pc version of a iptv program and it was subpar. this caused alot of the issues. whenever i add a new channel with tivimate, it does however mess up the channel list and you have to clear the cache and data and re-download the iptv channel list and guide.
