### ISSUE TITLE
Adding XMLTV Guide to Plex with existing HDHomeRun

### ISSUE THREAD

**Issue by russellmoran99** [ErsatzTV/ErsatzTV#913]
Hello, I am trying to add the XMLTV guide from ErsatzTV via the directions.  I already have a HDHomeRun I use for my Plex Live TV setup.  It says I cannot use XMLTV due to this.  Is there a work around or fix?  Thanks

**Comment by jasongdove** [comment]
I think you will want to use an IPTV aggregator/proxy like https://github.com/xteve-project/xTeVe

Perhaps following something like this? https://www.impostr-labs.com/setup-dizquetv-along-side-hdhomerun-ota-in-plex/

**Comment by Toylerrr** [comment]
You can add both but you will have to use an EPG/XMLTV for your area something like zap2xml or schedules direct no need to use xteve unless you want more control

**Comment by Joec6** [comment]
I just used the plex guide
Using multiple zip codes
So I'm in the middle of 3 major markets. Pick a zip for each market and match the channels.
Example of my guide result
Channel number3 is wfsb from iptv 3.1 is wfsb from hdhr
And so on.
