### ISSUE TITLE
[Feature Request] Disable force_original_aspect_ratio when scaling

### ISSUE THREAD

**Issue by Zebrazilla** [ErsatzTV/ErsatzTV#959]
I have a use case where I would like to indiscriminately scale content to fit a specific resolution, without taking aspect ratio into consideration.

Looking into the ffmpeg process as it runs I see that it uses **force_original_aspect_ratio=decrease,pad**, and reading up on these settings I think all I would need would be to not have force_original_aspect_ratio as an active parameter, and only have scale.

I could be wrong in my understanding however. If so, is there another way that this can be accomplished without touching the files themselves?

If possible, I think it'd be great if there were an _optional_ option for disabling adherence to original aspect ratio somewhere around here:
![image](https://user-images.githubusercontent.com/6796156/190053055-cff1f474-8598-4c9f-92bd-0e07abfb4279.png)

**Comment by Zebrazilla** [comment]
I don't have much experience with ffmpeg and did some experimenting. Not sure how useful this is but here goes!

It would seem that just setting scale didn't work, had to also set SAR for something to happen. Something like, if for example the target resolution is 640x480, gave me just the result I had in mind:
`scale=640:480,setsar=1`

**Comment by jasongdove** [comment]
Can you describe your use case a bit? I appreciate the solution suggestion, but would like to understand the problem first.

**Comment by Zebrazilla** [comment]
> Can you describe your use case a bit? I appreciate the solution suggestion, but would like to understand the problem first.

Sure, no problem, I can understand wanting to know more details. I'll try to elaborate as best I can.

One use case for me would be a movie channel that targets a 4:3 output, specifically 640x480, where the goal is to have only movies that have no black borders and fill the whole picture. In the schedule there are movies which are natively 4:3, however I would also like to include movies that are 16:9 and I would like these to fill out the whole 4:3. These 16:9 movies are usually open matte (whole 16:9 aspect ratio without black borders), which allows them to look okay when squeezed from 16:9 to 4:3, in my particular scenario where output is to a 4:3 screen.

Another use case for me would be when there are mixed media, where the entries in the schedule are sourced in such a way that they have no consistent, reliable aspect ratio. They may be cut off by an arbitrary amount either vertically or horizontally. In this case I would also like the output to be 4:3, 640x480, filling the whole picture. In this case the whole presentation being consistently 4:3, filling the whole picture, is more important than respecting the odd aspect ratio.

With force_original_aspect_ratio I would need to go through each individual piece of media and manually resize, meaning I'd have to reencode them and thus touch the files. This is possible but not ideal as I would very much prefer to leave the files themselves untouched, mainly so that they can be played differently outside of the ErsatzTV pipeline.

**Comment by jasongdove** [comment]
@Zebrazilla ETV develop builds now have a `Scaling Behavior` setting with a `Stretch` option that should behave as you describe.
